### PR TITLE
fix(kuma-cp): protocol check should be case insensitive

### LINKED ISSUE #4247: Deployment of gateway with kuma.io/protocol label with not lowercase value fails
### What happened?

# Summary 

When the user defines the `<port>.service.kuma.io/protocol: TCP` label we take the value as it is. In case the value is uppercase we might have an issue because in code we check only lowercase values: https://github.com/kumahq/kuma/blob/master/pkg/core/resources/apis/mesh/dataplane_helpers.go#L17, https://github.com/kumahq/kuma/blob/master/pkg/core/resources/apis/mesh/dataplane_validator.go#L227

and the user can observe error logs even if he defined value as `TCP` as the log says:
 
```
Dataplane	{"pod": "pod", "operationResult": "unchanged", "error": "admission webhook \"validator.kuma-admission.kuma.io\" denied the request: spec.networking.gateway.tags[\"kuma.io/protocol\"]: other values than TCP are not allowed"}
``` 

Should we allow providing case insensitive values in this field or be more strict and document that better?
In section 5.1 https://www.rfc-editor.org/rfc/rfc6335.html it looks like we shouldn't be strict with uppercase:
> Although service names may contain both upper-case and lower-case letters, case is ignored for 
    comparison purposes, so both "http" and "HTTP" denote the same service.

### PR DESCRIPTION
**Pull request by lukidzi**
### Summary

When protocol label is defined with uppercased value `TCP` deployment of gateway fails because it's different than `TCP`. 
We can discuss in issue if we want this way or maybe make it different way.
### Full changelog

* [Implement case insensitive comparision]
* [added to log information about provided protocol]

### Issues resolved

Fix #4247 

### Documentation

- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)

### Testing

- [X] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes

### Backwards compatibility

- [ ] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to take when upgrading.
- [ ] Add `backport-to-stable` label if the code follows our [backporting policy](/CONTRIBUTING.md#backporting)

### CODE REVIEW

**Comment by jakubdyszkiewicz** [comment]
do we also treat `kuma.io/protocol` as case insensitive down the road when we actually use it? Somewhere around outbound_proxy_generator.go etc.

**Comment by lukidzi** [comment]
In some places, we check lower cases by using https://github.com/kumahq/kuma/blob/master/pkg/core/resources/apis/mesh/dataplane_helpers.go#L26. Maybe the best option will be to lowercase that at `inbound_converter`.

**Comment by jakubdyszkiewicz** [comment]
I'm ok with lower-casing in inbound converter

**Comment by lahabana** [comment]
Decision from triage:
- Should not touch casing in validation (except fixing error message).
- In `inbound_converter.go` should lower case appProtocol/annotation.

File: pkg/core/resources/apis/mesh/dataplane_validator.go [hunk 1]
```diff
@@ -225,7 +225,7 @@ func validateGateway(gateway *mesh_proto.Dataplane_Networking_Gateway) validator
 		var result validators.ValidationError
 		if protocol, exist := selector[mesh_proto.ProtocolTag]; exist {
 			if protocol != ProtocolTCP {
-				result.AddViolationAt(path.Key(mesh_proto.ProtocolTag), `other values than TCP are not allowed`)
+				result.AddViolationAt(path.Key(mesh_proto.ProtocolTag), fmt.Sprintf(`other values than TCP are not allowed, provided value "%s"`, protocol))
```
Comment (lahabana) [inline pkg/core/resources/apis/mesh/dataplane_validator.go:228]:
```suggestion
				result.AddViolationAt(path.Key(mesh_proto.ProtocolTag), fmt.Sprintf(`other values than tcp are not allowed, provided value "%s"`, protocol))
```

If the right format is tcp maybe we should keep the log with tcp

**Review by jakubdyszkiewicz — APPROVED** [review]
