### PR TITLE
fix(hostnamegenerator): multizone syncing

### LINKED ISSUE #11041: Backwards compatibility of default HostnameGenerators
### Description

We now have `meshMultiZoneSelector`, a HostnameGenerator with this field might exist on global because of default HostnameGenerators. We have to make sure it doesn't cause problems when connecting a zone CP from the previous version

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**
### Checklist prior to review

Fix multizone syncing
* HG applied on global were not hashed when synced to Zone
* `kuma.io/zone` was missing on the default. xref https://github.com/kumahq/kuma/issues/11061
* Old zones were NACKing new HostnameGenerator. It would NACK all HostnameGenerators. I introduced a KDS flag to detect if we can sync HostnameGenerator with MeshMultiZoneService selector. Fix #11041

- [X] [Link to relevant issue][1] as well as docs and UI issues --
- [X] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [X] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [X] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [X] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

File: pkg/kds/context/context_test.go [hunk 1]
```diff
@@ -472,7 +472,7 @@ var _ = Describe("Context", func() {
 			var r model.Resource = core_mesh.NewCircuitBreakerResource()
 			switch given.scope {
 			case model.ScopeGlobal:
-				r = core_mesh.NewZoneIngressResource()
+				r = core_system.NewGlobalSecretResource()
```
Comment (jakubdyszkiewicz) [inline pkg/kds/context/context_test.go:475]: ZoneIngress is never provided by global

File: pkg/kds/context/context.go [hunk 2]
```diff
@@ -83,10 +84,16 @@ func DefaultContext(
 			RemoveStatus()),
 		reconcile.If(
 			reconcile.And(
-				reconcile.ScopeIs(core_model.ScopeMesh),
```
Comment (lobkovilya) [inline pkg/kds/context/context.go:86]: Why do we want to hash global-scoped resources now?

Comment (jakubdyszkiewicz) [reply pkg/kds/context/context.go:86]: To avoid conflicts. If a Global scoped resource can be applied on both global and zone CP, why wouldn't we hash it?

So far Global resources were
* GlobalSecret - we sync only signing key from global to zone
* Mesh - we sync as is without hashing
* Config - we sync selectively
* RBAC resources - we don't sync them

File: pkg/defaults/hostname_generator.go [hunk 3]
```diff
@@ -98,12 +98,15 @@ func EnsureHostnameGeneratorExists(ctx context.Context, resManager core_manager.
...
 		}
-		if err := ensureHostnameGeneratorExists(ctx, resManager, log, "synced-mesh-external-service", namespace, spec); err != nil {
+		if err := ensureHostnameGeneratorExists(ctx, resManager, log, "synced-mesh-external-service", namespace, nil, spec); err != nil {
 			return err
 		}
 	}
 
 	if cfg.Mode == core.Zone {
+		labels := map[string]string{
+			mesh_proto.ResourceOriginLabel: string(mesh_proto.ZoneResourceOrigin),
```
Comment (lobkovilya) [inline pkg/defaults/hostname_generator.go:108]: @Automaat don't we already set this automatically?

Comment (jakubdyszkiewicz) [reply pkg/defaults/hostname_generator.go:108]: yes, but on api level :/ See https://github.com/kumahq/kuma/issues/11061

Comment (lobkovilya) [reply pkg/defaults/hostname_generator.go:108]: I see, thanks for creating an issue

**Review by lobkovilya — APPROVED** [review]
