### PR TITLE
fix(api-server): skip display-name label for service insight

### LINKED ISSUE #9729: Skip display name ServiceInsight
### Description

We should not show display name label in ServiceInsight

### PR DESCRIPTION
**Pull request by Icarus9913**
This API would list the SeviceInsight resources with k8s mode, in which the common method [GetLabels](https://github.com/kumahq/kuma/blob/e21c751d782bc06eb7e8c779dacf71097bfe5732/pkg/plugins/resources/k8s/store.go#L299) would be called and supplement the `display-name` for the `Meta`.

So, let's just add a mapper function to remove that label in the API-Server component.

### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues -- close #9729 
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

File: pkg/api-server/service_insight_endpoints.go [hunk 1]
```diff
@@ -135,7 +144,12 @@ func (s *serviceInsightEndpoints) fillStaticInfo(name string, stat *v1alpha1.Ser
 // 2) Mesh+Name is a key on Universal, but not on Kubernetes, so if there are two services of the same name in different Meshes we would have problems with naming.
 // From the API perspective it's better to provide ServiceInsight per Service, not per Mesh.
 // For this reason, this method expand the one ServiceInsight resource for the mesh to resource per service
-func (s *serviceInsightEndpoints) expandInsights(serviceInsightList *mesh.ServiceInsightResourceList, nameContains string, filterFn func(service *v1alpha1.ServiceInsight_Service) bool) []rest.Resource {
+func (s *serviceInsightEndpoints) expandInsights(
+	serviceInsightList *mesh.ServiceInsightResourceList,
+	nameContains string,
+	filterFn func(service *v1alpha1.ServiceInsight_Service) bool,
+	mapperFn unversionedResourceMapper,
```
Comment (jakubdyszkiewicz) [inline pkg/api-server/service_insight_endpoints.go:151]: why do we need a mapper function here? Do we expect other implementations? If not, can't we just call removeDisplayNameLabel directly?

**Review by jakubdyszkiewicz — COMMENTED** [review]
please add a test

File: pkg/api-server/service_insight_endpoints.go (hunk 1 above)
Comment (Icarus9913) [reply pkg/api-server/service_insight_endpoints.go:151]: I was just wondering if we need other mapper implementations in the further, tha's why I write a `mapperFn` here. Surely we can just call `removeDisplayNameLabel` directly, let me do that.

**Comment by Icarus9913** [comment]
I'm adding the test

**Comment by Icarus9913** [comment]
Since our unit tests are written in universal memory cache store mode rather than k8s store mode, it's a little bit trivial to add/rewrite that framewrok. So, let's just add this label manually to the object that we store for the test.

File: pkg/api-server/testdata/service-insights/get.input.yaml [hunk 2]
```diff
@@ -5,6 +5,8 @@ name: mesh-1
 type: ServiceInsight
 mesh: mesh-1
 name: all-services-mesh-1
+labels:
+  kuma.io/display-name: all-services-mesh-1 # refer to https://github.com/kumahq/kuma/issues/9729
```
Comment (jakubdyszkiewicz) [inline pkg/api-server/testdata/service-insights/get.input.yaml:9]: I mean, I'd just write
```
# add display name manually to test if it's removed in the response
```
We can always refer to issue by git blame

**Review by jakubdyszkiewicz — APPROVED** [review]
