### PR TITLE
fix(meshmultizoneservice): order of matched mesh services

### LINKED ISSUE #11470: MeshMZService status updater seems to update even when there are no changes
### What happened?

```
2024-09-19T11:56:58.744Z	INFO	meshmultizoneservice.status-updater	updating matched mesh services	{"meshmultizoneservice": "demo-app-everywhere-cdzbd69dxz92wf94.kong-mesh-system", "matchedMeshServices": [{"name":"demo-app","namespace":"kuma-demo","zone":"east","mesh":"default"},{"name":"demo-app","namespace":"kuma-demo","zone":"west","mesh":"default"}]}
2024-09-19T11:57:03.743Z	INFO	meshmultizoneservice.status-updater	updating matched mesh services	{"meshmultizoneservice": "demo-app-everywhere-cdzbd69dxz92wf94.kong-mesh-system", "matchedMeshServices": [{"name":"demo-app","namespace":"kuma-demo","zone":"west","mesh":"default"},{"name":"demo-app","namespace":"kuma-demo","zone":"east","mesh":"default"}]}
2024/09/19 11:57:17 http: TLS handshake error from 10.40.1.2:52408: EOF
2024-09-19T11:57:18.743Z	INFO	meshmultizoneservice.status-updater	updating matched mesh services	{"meshmultizoneservice": "demo-app-everywhere-cdzbd69dxz92wf94.kong-mesh-system", "matchedMeshServices": [{"name":"demo-app","namespace":"kuma-demo","zone":"east","mesh":"default"},{"name":"demo-app","namespace":"kuma-demo","zone":"west","mesh":"default"}]}
2024-09-19T11:57:38.744Z	INFO	meshmultizoneservice.status-updater	updating matched mesh services	{"meshmultizoneservice": "demo-app-everywhere-cdzbd69dxz92wf94.kong-mesh-system", "matchedMeshServices": [{"name":"demo-app","namespace":"kuma-demo","zone":"west","mesh":"default"},{"name":"demo-app","namespace":"kuma-demo","zone":"east","mesh":"default"}]}
2024-09-19T11:57:48.744Z	INFO	meshmultizoneservice.status-updater	updating matched mesh services	{"meshmultizoneservice": "demo-app-everywhere-cdzbd69dxz92wf94.kong-mesh-system", "matchedMeshServices": [{"name":"demo-app","namespace":"kuma-demo","zone":"east","mesh":"default"},{"name":"demo-app","namespace":"kuma-demo","zone":"west","mesh":"default"}]}
```

Looks like the deepEqual doesn't work as expected:

https://github.com/kumahq/kuma/blob/735321cfb0b4ec7237bf2f8aa84d8d3745fb8ca5/pkg/core/resources/apis/meshmultizoneservice/status_updater.go#L117-L129

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**
### Checklist prior to review

Fix #11470

It was right when we added it, because it was just name which was a hashed name. It was then modified to also add namespace, zone and mesh here, so just sorting by name is not enough

- [ ] [Link to relevant issue][1] as well as docs and UI issues --
- [ ] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

File: pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/meshmultizoneservice.go [hunk 1]
```diff
@@ -63,3 +63,7 @@ type MatchedMeshService struct {
 	Zone      string `json:"zone"`
 	Mesh      string `json:"mesh"`
 }
+
+func (m MatchedMeshService) Hash() string {
```
Comment (lahabana) [inline pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/meshmultizoneservice.go:67]: It's more a FullyQualifiedName than a Hash.

**Review by lahabana — APPROVED** [review]
one nit but it makes sense!
