### PR TITLE
fix(gateway): delete service if Gateway unattached

### LINKED ISSUE #3597: Delete the GatewayInstance managed service when the Gateway unbinds
### Description

Say we have a GatewayInstance that is bound (by service tag matching) to a Kuma Gateway. In this case, `(*GatewayInstanceReconciler) createOrUpdateService()` will create and manage a service that is owned by the GatewayInstance.

Now, when the Kuma Gateway changes its service tags so that it is no longer bound to the GatewayInstance, `(*GatewayInstanceReconciler) createOrUpdateService()`  (correctly) fails to find the matching Kuma Gateway and doesn't reconcile the service. However, it ought to delete any previously created service since there are no longer any ports to expose.

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Summary

We leave the Deployment alone since it doesn't depend on the `Gateway`, but I'm not sure this is the expected behavior.

Blocked by #3570
Closes #3597

### CODE REVIEW

File: pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go [hunk 1]
```diff
@@ -92,14 +92,14 @@ func (r *GatewayInstanceReconciler) createOrUpdateService(
...
-		return nil, nil
-	}
-
 	obj, err := ctrls_util.CreateOrUpdateControlled(
 		ctx, r.Client, gatewayInstance, &kube_core.ServiceList{},
 		func(obj kube_client.Object) (kube_client.Object, error) {
+			// If we don't have a gateway, we don't want our Service anymore
+			if gateway == nil {
+				return nil, nil
+			}
```
Comment (jpeach) [inline pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go:101]: WDYT about adding a `ctrls_util.DeleteControlled()` - would that make the behavior more obvious?

Comment (michaelbeaumont) [reply pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go:101]: I added more to the godoc and renamed the function. I personally like the abstraction of having `mutate` decide whether to delete the object by explicitly returning `nil` as an option type, vs having to call multiple, more "imperative" functions.

Comment (jpeach) [reply pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go:101]: OK, I think the renaming makes sense :+1:

**Review by jpeach — APPROVED** [review]
