### PR TITLE
fix(api-server): support zone listeners in _layout inspect

### LINKED ISSUE #16343: Inspect API support for new dataplane listener kinds: ZoneIngress and ZoneEgress
### Description

https://github.com/kumahq/kuma/pull/15759 introduced new listener types. We need to ensure the `/_layout`-based Inspect API properly supports and renders these listeners.

### PR DESCRIPTION
**Pull request by slonka**
## Motivation

Include ZoneIngress and ZoneEgress listeners in the dataplane `/_layout` response.

## Implementation information

- Added a new `listeners` field to the `DataplaneLayout` schema (`api/openapi/specs/api.yaml`) backed by a new `DataplaneListener` type (`api/openapi/specs/common/resource.yaml`) with `kri`, `type` (`ZoneIngress` / `ZoneEgress`), `port`, and `proxyResourceName`.
- Updated `pkg/api-server/dataplane_layout_endpoint.go` to populate `listeners` from `dataplane.networking.listeners` instead of mixing zone proxy listeners into `inbounds`. Unknown listener kinds are skipped rather than failing the request.
- Centralized listener section name handling so unnamed listeners fall back to the port (`Listener.GetSectionName()`).

## Supporting documentation

Fix https://github.com/kumahq/kuma/issues/16343

> Changelog: feat(kuma-cp): add mesh-scoped zone proxies

### CODE REVIEW

File: pkg/api-server/dataplane_layout_endpoint.go [hunk 1]
```diff
@@ -97,6 +98,24 @@ func (dle *dataplaneLayoutEndpoint) getLayout(request *restful.Request, response
...
+			proxyResourceName = naming.ContextualZoneEgressListenerName(sectionName)
+		default:
+			continue
+		}
+		inbounds = append(inbounds, api_common.DataplaneInbound{
+			Kri:               kri.WithSectionName(kri.From(dataplane), sectionName).String(),
+			Port:              int32(listener.GetPort()),
+			Protocol:          core_meta.ProtocolTCP.String(),
+			ProxyResourceName: proxyResourceName,
+		})
```
Comment (lahabana) [inline pkg/api-server/dataplane_layout_endpoint.go:121]: Do we really want to show listeners as inbounds in the API? Don't they have significant enough difference that hiding this out will cause problems/confusions to the consumer of the API?

File: api/openapi/types/common/zz_generated.resource.go [hunk 2]
```diff
@@ -1,14 +1,44 @@
 // Package types provides primitives to interact with the openapi HTTP API.
 //
-// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
+// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
```
[the remark this answers is not in the document]
Comment (slonka) [reply api/openapi/types/common/zz_generated.resource.go:3]: will be fixed by https://github.com/kumahq/kuma/pull/16456

File: pkg/api-server/dataplane_layout_endpoint.go (hunk 1 above)
Comment (slonka) [reply pkg/api-server/dataplane_layout_endpoint.go:121]: you're right

File: pkg/xds/generator/zone_proxy_listener_generator.go [hunk 3]
```diff
@@ -102,7 +102,7 @@ func (g ZoneProxyListenerGenerator) generateIngressListener(
 	address := listener.Address
 	port := listener.Port
 
-	listenerName := naming.ContextualZoneIngressListenerName(listener.Name)
+	listenerName := naming.ContextualZoneIngressListenerName(listener.GetSectionName())
```
Comment (lobkovilya) [inline pkg/xds/generator/zone_proxy_listener_generator.go:105]: Nice catch!

**Review by lobkovilya — APPROVED** [review]
LGTM
