### PR TITLE
test(e2e): multizone environment

### LINKED ISSUE #4120: Speedup E2E tests with mesh/suite isolation
# Problem

Our unit tests are highly "parallelizable" on one machine, meaning that I can easily speed them up by adding more cores. My workstation is doing 100% CPU while executing them.

This is not the case for our E2E tests. We are dealing with the eventual consistency of Kuma & Kubernetes therefore we have to wait a lot. We "solve" that by splitting test suites and leveraging multiple VMs. It's impossible to execute E2E on a single machine within a reasonable timeframe (it takes probably ~2h).

The time we waste a lot is:
* redeploying Kuma to have a clean slate. We try to avoid this by using BeforeSuite for setup, but not with every test
* waiting for resources to be cleaned up (removing a namespace takes forever)

This results in slow CI which hurts engineering agility.

## Environments

The solution is to have predefined environments and share the Kuma deployment among them.

The environments we need are:
### Standalone Universal
Universal is meant to be used on production with Postgres therefore we should switch our setup to test more with postgres.
If it will take too much overhead, we can introduce parameter to switch to builtin storage to have a quicker E2E loop when we develop new tests

### Standalone Kubernetes

Deployed with HELM + init container.

### Multizone
This one is the hardest because there can be many combinations of global/zone cps living on Universal/Kubernetes. We can cover majority of things by spawning:
* Global on Universal. We do this for majority of time because we don't want to take one of two K8S clusters
* Kube Zone 1
* Kube Zone 2
* Universal Zone 1
* Universal Zone 2

With such setup, we can cover cross-zone communication across all environments.

**How to test Global CP with Multizone then?**
The only operation that we do on Global CP are:
* manage Kuma resources
* retrieving IPs.
* generate tokens
If we abstract away managing resources, we can decide if Global is Universal or Kubernetes when we setup the environment and run same tests with both.

### Exceptions
While we can cover about ~90% of tests with setup above, there will be exceptions. That's ok. We can just follow our current pattern. Exceptions that I can see right now are
* CP autoscaling (we can probably squeeze this into environment)
* Upgrades / Rollbacks
* Reliability tests (they restart CP a lot which may or may not be a problem)

## Isolation within the environment

To achieve isolation, we can use different meshes and namespaces for every test suite.
It will improve our testing of running multiple meshes.

We should be able to parallelize tests in one environment. There is no reason we cannot test faultinjection in mesh-1 and ratelimitting in mesh-2. Because we can parallelize them, we can shift our tests to properly utilize CPU.

It forces us to not use pattern of not cleaning up and recreate environment. If you really need isolation - use mesh.

We should also be able to split tests of one environment to multiple VMs as we do now. I expect that tests execution will improve in 10x factor or more, but we may still get to the point that executing all tests of one environment sequentially is a problem.

## Test-specific CP config

Sometimes we run tests under the condition that we configured CP in a specific way (CP configuration, not Mesh configuration). The examples are
* experimental features
* CNI
* KUMA_METRICS_ZONE_IDLE_TIMEOUT 10s

The solution for this would be to run one zone with experimental features. For example, one Kubernetes zone can be run with CNI, and a second with init-container.

## HELM vs kumactl

We can deploy one zone with HELM and the second with kumactl to test both deployment methods.

## Test High Availability by default

We don't test HA that much in our tests. Because we won't bring CP up and down all the time, we can run 2 instances of each CP for at least multizone deployment and standalone kubernetes.

## Test backward compatibility by default

That might be controversial, because it may be inconvenient, but I'd try to test backwards compatibility by default.
For this, Kube Zone 2 and Universal Zone 2 could be running the old version of Zone CP.
The majority of features should be testable with multizone even if we have one old CP.

This is NOT the same as upgrade/rollback tests, but it can uncover a lot of potential problems.

## Waiting for resources to be cleaned up

Removing a namespace takes forever. Because we would have isolation we can trigger delete of a namespace but we don't have to wait for it to actually be cleaned up.

## Migration path from current tests

We can gradually migrate tests from our current approach, by writing new test within the environment and slowly bringing the old tests to the environments. We don't have to do "stop the world, migrate everything" for X weeks.

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**
### Summary

Adds multizone E2E environment for parallelized tests.

### Issues resolved

Fix #4120

### Documentation

~- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)~

### Testing

- [ ] Unit tests
- [X] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes

### Backwards compatibility

~- [ ] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to take when upgrading.~
~- [ ] Add `backport-to-stable` label if the code follows our [backporting policy](/CONTRIBUTING.md#backporting)~

### CODE REVIEW

File: test/e2e_env/multizone/multizone_suite_test.go [hunk 1]
```diff
@@ -0,0 +1,178 @@
...
+		Expect(env.Global.Install(Kuma(core.Global,
+			WithEnv("KUMA_STORE_UNSAFE_DELETE", "true"),
+		))).To(Succeed())
+
+		wg := sync.WaitGroup{}
+		wg.Add(4)
+
+		env.KubeZone1 = NewK8sCluster(NewTestingT(), Kuma1, Verbose)
+		go func() {
+			Expect(env.KubeZone1.Install(Kuma(core.Zone,
```
Comment (lobkovilya) [inline test/e2e_env/multizone/multizone_suite_test.go:44]: do we need `defer GinkgoRecover()` for goroutines with assertions?

File: test/e2e_env/multizone/multizone_suite_test.go [hunk 2]
```diff
@@ -0,0 +1,178 @@
...
+			))).To(Succeed())
+			wg.Done()
+		}()
+
+		env.KubeZone2 = NewK8sCluster(NewTestingT(), Kuma2, Verbose)
+		go func() {
+			Expect(env.KubeZone2.Install(Kuma(core.Zone,
+				WithEnv("KUMA_STORE_UNSAFE_DELETE", "true"),
+				WithIngress(),
+				// WithEgress(),
```
Comment (lobkovilya) [inline test/e2e_env/multizone/multizone_suite_test.go:58]: did you leave it intentionally?

File: test/e2e_env/multizone/multizone_suite_test.go [hunk 3]
```diff
@@ -0,0 +1,178 @@
...
+		env.UniZone1 = NewUniversalCluster(NewTestingT(), Kuma4, Silent)
+		E2EDeferCleanup(env.UniZone1.DismissCluster) // clean up any containers if needed
+		go func() {
+			err := NewClusterSetup().
+				Install(Kuma(core.Zone,
+					WithGlobalAddress(env.Global.GetKuma().GetKDSServerAddress()),
+					WithEnv("KUMA_STORE_UNSAFE_DELETE", "true"),
+				)).
+				Install(IngressUniversal(env.Global.GetKuma().GenerateZoneIngressToken)).
+				// Install(EgressUniversal(env.Global.GetKuma().GenerateZoneEgressToken)).
```
Comment (lobkovilya) [inline test/e2e_env/multizone/multizone_suite_test.go:73]: and this and same for UniZone2

File: test/e2e_env/multizone/trafficpermission/trafficpermission.go [hunk 4]
```diff
@@ -0,0 +1,178 @@
...
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+
+	core_mesh "github.com/kumahq/kuma/pkg/core/resources/apis/mesh"
+	"github.com/kumahq/kuma/test/e2e_env/multizone/env"
+	. "github.com/kumahq/kuma/test/framework"
+)
+
+func TrafficPermission() {
+	const meshName = "tp-test"
+	const namespace = "tp-test"
```
Comment (lobkovilya) [inline test/e2e_env/multizone/trafficpermission/trafficpermission.go:18]: Can we autogenerate this using UUID suffix for example?

**Review by lobkovilya — APPROVED** [review]

File: test/e2e_env/multizone/multizone_suite_test.go (hunk 1 above)
Comment (jakubdyszkiewicz) [reply test/e2e_env/multizone/multizone_suite_test.go:45]: we do. Thanks, added.

File: test/e2e_env/multizone/multizone_suite_test.go (hunk 2 above)
Comment (jakubdyszkiewicz) [reply test/e2e_env/multizone/multizone_suite_test.go]: That was commented because there was a bug, but it's fixed in master now. Restored

File: test/e2e_env/multizone/trafficpermission/trafficpermission.go (hunk 4 above)
Comment (jakubdyszkiewicz) [reply test/e2e_env/multizone/trafficpermission/trafficpermission.go:18]: I'd prefer to keep the name stable. It's easier to work with a test if you don't have to extract the mesh/namespace main from the test with every run.

Comment (lobkovilya) [reply test/e2e_env/multizone/trafficpermission/trafficpermission.go:18]: Maybe we can construct it somehow using `ginkgo.CurrentGinkgoTestDescription()`:
```go
//GinkgoTestDescription represents the information about the current running test returned by CurrentGinkgoTestDescription
//	FullTestText: a concatenation of ComponentTexts and the TestText
//	ComponentTexts: a list of all texts for the Describes & Contexts leading up to the current test
//	TestText: the text in the actual It or Measure node
//	IsMeasurement: true if the current test is a measurement
//	FileName: the name of the file containing the current test
//	LineNumber: the line number for the current test
//	Failed: if the current test has failed, this will be true (useful in an AfterEach)
type GinkgoTestDescription struct {
	FullTestText   string
	ComponentTexts []string
	TestText       string

	IsMeasurement bool

	FileName   string
	LineNumber int

	Failed   bool
	Duration time.Duration
}
```
but it's not a blocker for this PR

Comment (jakubdyszkiewicz) [reply test/e2e_env/multizone/trafficpermission/trafficpermission.go:18]: it is an option, but not sure about length and spaces, etc. I'd keep this static and do autogeneration if we ever found this problematic

**Review by michaelbeaumont — APPROVED** [review]
LGTM
