### PR TITLE
fix(kuma-cp) broken SDS auth and XDS generation on rapid DP restarts

### LINKED ISSUE #2102: Dataplanes sending empty jwt when restarting many services
### Summary

I've been testing a universal deployment on a cluster of 8 VMs. Each node runs 11 agent dataplane services, for a total of 88 dps (+ some management dataplanes that run on one node). All services / dataplanes are backed by systemd units.

If I restart all agent services on all nodes at the same time I can frequently (~ 50% of the time) get into a situation where the dp sends an empty token. I see many messages in my console like this:

```Jun 04 20:24:18 node3 kuma-dp[26777]: [2021-06-04 20:24:18.821][27084][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] StreamSecrets gRPC config stream closed: 2, authentication failed: could not parse token : token contains an invalid number of segments```

`kumactl inspect dataplanes` shows `never` for `CERT REGENERATED AGO`:

```
MESH      NAME                                                  TAGS                                                                                         STATUS   LAST CONNECTED AGO   LAST UPDATED AGO   TOTAL UPDATES   TOTAL ERRORS   CERT REGENERATED AGO   CERT EXPIRATION       CERT REGENERATIONS   KUMA-DP VERSION      ENVOY VERSION   NOTES
default   emf-device-agent-d137cd8af61eaf44a224c1171c215896     kuma.io/protocol=http2 kuma.io/service=emf-device-agent-d137cd8af61eaf44a224c1171c215896     Online   11m                  10m                13              0              never                  -                     0                    1.1.6-10-gccfb1836   1.17.1
```

When the cluster enters this state, none of the effected services can communicate with each other.

Is it expected that restarting many dataplanes at the same time will cause an issue?

Please let me know any more debug I can provide.

### Additional Details & Logs

- Version: 1.1.6-10-gccfb1836
- Configuration: Universal
- Platform and Operating System: CentOS 7.9 VBox VMs

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**
### Summary

This is second take on #2327 which solves #2102.

Fix #2102

#### The problem

XDS logic was built with assumption that there is only one xDS (ADS) stream from data plane proxy to the control plane.
This is true for majority of cases but when you rapidly restart kuma-dp, there might be a situation when there is old stream which is still not closed and a new stream.

For example, XDS watchdog was run only once for all stream (which is correct), but it was using StreamID of the old stream when new stream was connected.
This caused DataplaneMetadata to be empty (XDS sync package was retriving it using old StreamID) which then caused SDS to be configured with empty DP token.

Additionaly, XDS watchdog could be stopped because of this out of sync events and DP lifecycle could unregister DP.

##### Callbacks

I noticed that XDS callbacks provided by go-control-plane are very incovenient for our use case.
We don't know what is the proxyID on OnStreamOpen and OnStreamClose, therefore we need to follow the mapping StreamID->Dataplane.
We want to run Watchdog, follow DataplaneMetadata etc. but for the data plane proxy, not for a stream.
Additionally, we only care about the case when first DiscoveryRequest is sent.

I introduced a new set of Callbacks called DataplaneCallbacks that are then converted to XDS callbacks.
This lets us to build a new callbacks with DP context in mind without rebuilding the logic in every callback implementation.

Those callbacks follows all the stream for given dataplane therefore we can react when first stream is connected or last is disconnected.
This let us then write more resilient callbacks that take into account edge case of having many streams for Dataplane.

As a next step I dropped dependency on stream ID in `xds/sync` package. This package should not care about stream ID which is internal concept for XDS server.

We can still use "raw" xDS callbacks if we need (for example for stats).

##### Metadata

I added extra check whether metadata is not nil (should not be a case with new callbacks) that will prevent us for generating invalid XDS config.

### Documentation

- [X] No docs.

### Testing

- [X] Unit tests
- [ ] E2E tests - it's very hard to build E2E for this.
- [X] Manual testing on Universal
- [ ] Manual testing on Kubernetes 

### Backwards compatibility

- [X] Add `backport-to-stable` label.

### CODE REVIEW

File: pkg/xds/server/callbacks/dataplane_callbacks.go [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+	dpKey := proxyId.ToResourceKey()
+	metadata := core_xds.DataplaneMetadataFromXdsMetadata(request.Metadata())
+	if metadata == nil {
+		return errors.New("metadata in xDS Node cannot be nil")
+	}
+
+	d.Lock()
+	dpStream := d.dpStreams[streamID]
+	dpStream.dp = &dpKey
+	d.dpStreams[streamID] = dpStream
```
Comment (lobkovilya) [inline pkg/xds/server/callbacks/dataplane_callbacks.go:108]: Interesting, I didn't know you can't do `d.dpStreams[streamID].dp = &dpKey` in GoLang, but that's of course makes sense :)

File: pkg/xds/server/callbacks/dataplane_callbacks.go [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+// in one instance of CP and a new stream in a new instance of CP.
+//
+// Those callbacks may be also used with SDS. In case of SDS, at this moment Envoy creates many SDS streams to the Control Plane.
+type DataplaneCallbacks interface {
+	// OnStreamConnected is executed when Dataplane is connected to the control plane (go-control-plane's OnStreamOpen)
+	// and Dataplane executes the first request (go-control-plane's OnStreamRequest, only in this phase we can extract Dataplane and DataplaneMetadata).
+	// If there are many xDS stream this callback is executed for every new xDS stream.
+	OnStreamConnected(streamID core_xds.StreamID, dpKey core_model.ResourceKey, ctx context.Context, metadata core_xds.DataplaneMetadata) error
+	// OnFirstStreamConnected is similar to OnStreamConnected but if there are many xDS streams, it is only executed for the first stream.
+	OnFirstStreamConnected(streamID core_xds.StreamID, dpKey core_model.ResourceKey, ctx context.Context, metadata core_xds.DataplaneMetadata) error
```
Comment (lobkovilya) [inline pkg/xds/server/callbacks/dataplane_callbacks.go:30]: When I read the interface for the first time I was thinking about the order of calls:
1. OnFirstStreamConnected
2. OnStreamConnected
3. OnStreamDisconnected
4. OnLastStreamDisconnected

In fact I think you have 1 and 2 switched. I'm not convinced here, maybe it's fine.

Also, when you see 2 methods:
- OnFirstStreamConnected
- OnStreamConnected

You may have an idea that method `OnStreamConnected` won't be called in case `OnFirstStreamConnected` was called.

And I don't really like the fact that we don't support many streams per Proxy, but at the same time this interface tells you the opposite.

Maybe we should rename the methods like:
- OnFirstStreamConnected -> OnProxyConnected
- OnStreamConnected -> OnProxyReconnected
- OnStreamConnected -> just drop it
- OnLastStreamDisconnected -> OnProxyDisconnected

WDYT?

**Review by lobkovilya — COMMENTED** [review]
I really like this refactoring and how some of the Callbacks became simple. I have a few comments, I'm not really stubborn about them (especially the last one), just wanted to start a discussion

File: pkg/xds/server/callbacks/dataplane_callbacks.go (hunk 2 above)
Comment (jakubdyszkiewicz) [reply pkg/xds/server/callbacks/dataplane_callbacks.go]: Thank you!! I was struggling a bit with naming here. I very much like `OnProxyConnected`, `OnProxyReconnected`, `OnProxyDisconnected`

File: pkg/xds/server/callbacks/dataplane_callbacks.go [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+// In the ideal world we could assume that one Dataplane has one xDS stream.
+// Due to race network latencies etc. there might be a situation when one Dataplane has many xDS streams for the short period of time.
+// Those callbacks helps us to deal with such situation.
+//
+// Keep in mind that it does not solve many xDS streams across many instances of the Control Plane.
+// If there are many instances of the Control Plane and Dataplane reconnects, there might be an old stream
+// in one instance of CP and a new stream in a new instance of CP.
+//
+// Those callbacks may be also used with SDS. In case of SDS, at this moment Envoy creates many SDS streams to the Control Plane.
+type DataplaneCallbacks interface {
```
[the remark this answers is not in the document]
Comment (jakubdyszkiewicz) [reply pkg/xds/server/callbacks/dataplane_callbacks.go:24]: I don't know about this one. If we change this to ProxyCallbacks then for example DataplaneMetadata should be also changed to ProxyMetadata.

Is ZoneIngress a Proxy?
Is ZoneIngress a Dataplane?
Is Proxy a Dataplane or many Proxies are a Dataplane?

I think we need to gather as a team and discuss what exactly is Dataplane, Proxy, ZoneIngress and figure out ubiquitous language for it.

File: pkg/xds/server/callbacks/dataplane_callbacks.go [hunk 4]
```diff
@@ -0,0 +1,146 @@
...
+	// OnProxyConnected is executed when proxy is connected after it was disconnected before.
+	OnProxyConnected(streamID core_xds.StreamID, dpKey core_model.ResourceKey, ctx context.Context, metadata core_xds.DataplaneMetadata) error
+	// OnProxyReconnected is executed when proxy is already connected, but there is another stream.
+	// This can happen when there is a delay with closing the old connection from the proxy to the control plane.
+	OnProxyReconnected(streamID core_xds.StreamID, dpKey core_model.ResourceKey, ctx context.Context, metadata core_xds.DataplaneMetadata) error
+	// OnProxyDisconnected is executed only when the last stream of the proxy disconnects.
+	OnProxyDisconnected(streamID core_xds.StreamID, dpKey core_model.ResourceKey)
```
Comment (jpeach) [inline pkg/xds/server/callbacks/dataplane_callbacks.go:31]: Should we pass the stream context here too?

Comment (lobkovilya) [reply pkg/xds/server/callbacks/dataplane_callbacks.go:31]: I'm not sure. Original interface for xds callbacks doesn't have a `context` in `OnStreamClosed`:
```go// Callbacks defines Callbacks for xDS streaming requests. The difference over real go-control-plane Callbacks is that it takes an DiscoveryRequest / DiscoveryResponse interface.
// It helps us to implement Callbacks once for many different versions of Envoy API.
type Callbacks interface {
	// OnStreamOpen is called once an xDS stream is opened with a stream ID and the type URL (or "" for ADS).
	// Returning an error will end processing and close the stream. OnStreamClosed will still be called.
	OnStreamOpen(context.Context, int64, string) error
	// OnStreamClosed is called immediately prior to closing an xDS stream with a stream ID.
	OnStreamClosed(int64)
	// OnStreamRequest is called once a request is received on a stream.
	// Returning an error will end processing and close the stream. OnStreamClosed will still be called.
	OnStreamRequest(int64, DiscoveryRequest) error
	// OnStreamResponse is called immediately prior to sending a response on a stream.
	OnStreamResponse(int64, DiscoveryRequest, DiscoveryResponse)
}
```
I know that we store the `context` in the map for each streamID, but do we really need this? Probably it has `Err()` or `Deadline()` that kind of limits the way of using it.

But that's fairly simple to add, I can do it if needed

Comment (jpeach) [reply pkg/xds/server/callbacks/dataplane_callbacks.go:31]: If there's no current need for it, there's no need to add it in this PR :)

File: pkg/xds/server/callbacks/dataplane_callbacks.go [hunk 5]
```diff
@@ -0,0 +1,146 @@
...
+		return errors.Wrap(err, "invalid node ID")
+	}
+	dpKey := proxyId.ToResourceKey()
+	metadata := core_xds.DataplaneMetadataFromXdsMetadata(request.Metadata())
+	if metadata == nil {
+		return errors.New("metadata in xDS Node cannot be nil")
+	}
+
+	d.Lock()
+	dpStream := d.dpStreams[streamID]
```
Comment (jpeach) [inline pkg/xds/server/callbacks/dataplane_callbacks.go:101]: Not sure whether streamID semantics allow this to happen, but if a stream opens 2 concurrent requests, then we could increment the active streams once too many. We can mitigate this by checking "d.dpStreams[streamID].dp != nil" again once we have the write lock.

**Review by jpeach — APPROVED** [review]
