### PR TITLE
fix(MeshGateway): fix MeshTCPRoute on MeshGateway

### LINKED ISSUE #9154: MeshGateway error with MeshTCPRoute
### What happened?

I'm hitting:

```
2024-02-06T19:43:16.748Z	ERROR	xds-server.dataplane-sync-watchdog	OnTick() failed	{"dataplaneKey": {"Mesh":"default","Name":"tcp-gateway-86b988965-kxbbr.microservice-mesh"}, "error": "interface conversion: interface {} is v1alpha1.Rule, not v1alpha1.RuleConf", "errorVerbose": "interface conversion: interface {} is v1alpha1.Rule, not v1alpha1.RuleConf\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick.func1\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/util/watchdog/watchdog.go:62\nruntime.gopanic\n\truntime/panic.go:914\nruntime.panicdottypeE\n\truntime/iface.go:263\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.GenerateEnvoyRouteEntries\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/gateway.go:79\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.sortRulesToHosts\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go:185\ngithub.com/kumahq/kuma/pkg/plugins/policies/core/xds/meshroute.CollectListenerInfos\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/core/xds/meshroute/gateway.go:98\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.ApplyToGateway\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go:122\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.plugin.Apply\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go:58\ngithub.com/kumahq/kuma/pkg/plugins/policies/core/generator.generator.Generate\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/core/generator/generator.go:23\ngithub.com/kumahq/kuma/pkg/xds/generator/core.CompositeResourceGenerator.Generate\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/generator/core/resource_generator.go:22\ngithub.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateProfileSource).Generate\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/generator/proxy_template.go:76\ngithub.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateGenerator).Generate\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/generator/proxy_template.go:28\ngithub.com/kumahq/kuma/pkg/xds/server/v3.(*TemplateSnapshotGenerator).GenerateSnapshot\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/server/v3/reconcile.go:168\ngithub.com/kumahq/kuma/pkg/xds/server/v3.(*reconciler).Reconcile\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/server/v3/reconcile.go:55\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncDataplane\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/sync/dataplane_watchdog.go:148\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).Sync\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/sync/dataplane_watchdog.go:79\ngithub.com/kumahq/kuma/pkg/xds/sync.(*dataplaneWatchdogFactory).New.func2\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/sync/dataplane_watchdog_factory.go:43\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/util/watchdog/watchdog.go:70\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/util/watchdog/watchdog.go:40\nruntime.goexit\n\truntime/asm_amd64.s:1650"}
```

When applying:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: tcp-gateway
  namespace: microservice-mesh
  labels:
    kuma.io/origin: zone
spec:
  replicas: 1
  serviceType: LoadBalancer
  tags:
    kuma.io/service: tcp-gateway
---
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
metadata:
  name: tcp-gateway
  labels:
    kuma.io/origin: zone
mesh: default
spec:
  selectors:
    - match:
        kuma.io/service: tcp-gateway
  conf:
    listeners:
      - port: 90
        protocol: TCP
---
apiVersion: kuma.io/v1alpha1
kind: MeshTCPRoute
metadata:
  name: tcp-gateway
  namespace: kong-mesh-system
  labels:
    kuma.io/origin: zone
spec:
  targetRef:
    kind: MeshGateway
    name: tcp-gateway
  to:
    - targetRef:
        kind: Mesh
      rules:
        - default:
            backendRefs:
              - kind: MeshService
                name: api-play-001_microservice-mesh_svc_8080
```

Pretty print of the stacktrace;
```
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/util/watchdog/watchdog.go:62
runtime.gopanic
	runtime/panic.go:914
runtime.panicdottypeE
	runtime/iface.go:263
github.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.GenerateEnvoyRouteEntries
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/gateway.go:79
github.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.sortRulesToHosts
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go:185
github.com/kumahq/kuma/pkg/plugins/policies/core/xds/meshroute.CollectListenerInfos
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/core/xds/meshroute/gateway.go:98
github.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.ApplyToGateway
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go:122
github.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.plugin.Apply
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go:58
github.com/kumahq/kuma/pkg/plugins/policies/core/generator.generator.Generate
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/core/generator/generator.go:23
github.com/kumahq/kuma/pkg/xds/generator/core.CompositeResourceGenerator.Generate
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/generator/core/resource_generator.go:22
github.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateProfileSource).Generate
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/generator/proxy_template.go:76
github.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateGenerator).Generate
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/generator/proxy_template.go:28
github.com/kumahq/kuma/pkg/xds/server/v3.(*TemplateSnapshotGenerator).GenerateSnapshot
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/server/v3/reconcile.go:168
github.com/kumahq/kuma/pkg/xds/server/v3.(*reconciler).Reconcile
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/server/v3/reconcile.go:55
github.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncDataplane
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/sync/dataplane_watchdog.go:148
github.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).Sync
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/sync/dataplane_watchdog.go:79
github.com/kumahq/kuma/pkg/xds/sync.(*dataplaneWatchdogFactory).New.func2
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/sync/dataplane_watchdog_factory.go:43
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/util/watchdog/watchdog.go:70
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/util/watchdog/watchdog.go:40
runtime.goexit
	runtime/asm_amd64.s:1650
```

### PR DESCRIPTION
**Pull request by lahabana**
- MeshTCPRoute when applied to a MeshGateway would panic thus making it unusable. This fixes this and backfills e2e tests
- Refactor tests to make them easier to maintain

Fix #9154

### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues --
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

File: pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go [hunk 1]
```diff
@@ -136,7 +136,7 @@ func sortRulesToHosts(
 	return meshroute.SortByHostname(hostInfosByHostname)
 }
 
-func GenerateEnvoyRouteEntries(host plugin_gateway.GatewayHost, toRules []ruleByHostname) []route.Entry {
+func generateEnvoyRouteEntries(host plugin_gateway.GatewayHost, toRules []ruleByHostname) []route.Entry {
```
Comment (slonka) [inline pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go:139]: could it have been called from a parent project? if not then 👍 to making it private

File: pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go [hunk 2]
```diff
@@ -705,32 +705,38 @@ var _ = Describe("MeshTCPRoute", func() {
 
 			rules := core_rules.Rule{
 				Subset: core_rules.MeshSubset(),
-				Conf: api.RuleConf{
-					BackendRefs: []common_api.BackendRef{{
-						TargetRef: builders.TargetRefService("backend"),
-						Weight:    pointer.To(uint(100)),
-					}},
+				Conf: api.Rule{
```
Comment (slonka) [inline pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go:708]: can we do something about such mistakes at compile time? can we have some static analysis tool to check that we're casting `Conf` to something that always `Default`?

**Review by slonka — APPROVED** [review]
Overall good 👍. I think we should spend some time thinking about how to avoid such errors in the future. Can we have some static analysis tools that would catch it? Should we reenable code coverage? Or should we just be more vigilant on reviews and always require an E2E test?

File: pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go (hunk 1 above)
Comment (lahabana) [reply pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go:139]: It's not

File: pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go (hunk 2 above)
Comment (lahabana) [reply pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go:708]: I thought about a few things (like an interface to implement etc). But I couldn't find a good idea I'm open to suggestions if you have a good idea!

Comment (lahabana) [reply pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go:708]: Maybe it must have a `Default` entry...

Comment (michaelbeaumont) [reply pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go:708]: Yes, just a marker trait with a method like "IsPolicyConf" is probably enough, that it won't end up being implemented twice
