### PR TITLE
fix(MeshLoadBalancingStrategy): skip configure endpoints due to different mesh

### LINKED ISSUE #14109: zone cp panic when using egress
### Kuma Version

2.7.13

### Describe the bug

I noticed nil pointer panic in Zone CP when using Egress with multiple meshes resources, also I used MeshLoadBalancingStrategy policy

### To Reproduce

1. Deploy a multizone deployments with Egress enabled:
   * Global
   * Zone-1
   * Zone-2

2. Created 2  Mesh resources

```yaml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: dev
spec:
  routing:
    zoneEgress: true
  mtls:
    enabledBackend: ca-1
    backends:
    - name: ca-1
      type: builtin
---
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: int
spec:
  routing:
    zoneEgress: true
  mtls:
    enabledBackend: ca-1
    backends:
    - name: ca-1
      type: builtin
```

3. Create different mesh services in different zones
     * create a `nginx` in `dev` mesh
     * create a `httpbin` in `int` mesh

4. Apply the following MeshLoadBalancingStrategy policies

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshLoadBalancingStrategy
metadata:
  name: dev-allow-crosszone-failover
  namespace: kuma-system
  annotations:
    kuma.io/display-name: dev-allow-crosszone-failover
  labels:
    kuma.io/mesh: dev
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: Mesh
    default:
      localityAwareness:
        crossZone:
          failover:
          - to:
              type: Any
---
apiVersion: kuma.io/v1alpha1
kind: MeshLoadBalancingStrategy
metadata:
  name: int-allow-crosszone-failover
  namespace: kuma-system
  labels:
    kuma.io/mesh: int
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: Mesh
    default:
      localityAwareness:
        crossZone:
          failover:
          - to:
              type: Any
```

4. Check the Zone CP logs

### Expected behavior

No panic hit.

### Additional context (optional)

Zone CP error logs:

```text
2025-08-01T08:30:27.444Z	ERROR	xds-server.dataplane-sync-watchdog	OnTick() failed	{"dataplaneKey": {"Mesh":"","Name":"kuma-egress-5b8b69dd86-8xhgr.kuma-system"}, "error": "runtime error: invalid memory address or nil pointer dereference", "errorVerbose": "runtime error: invalid memory address or nil pointer dereference\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick.func1\n\tgithub.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:62\nruntime.gopanic\n\truntime/panic.go:792\nruntime.panicmem\n\truntime/panic.go:262\nruntime.sigpanic\n\truntime/signal_unix.go:925\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1.configureEndpoints\n\tgithub.com/kumahq/kuma/pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go:137\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1.plugin.configureEgress\n\tgithub.com/kumahq/kuma/pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go:257\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1.plugin.Apply\n\tgithub.com/kumahq/kuma/pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go:50\ngithub.com/kumahq/kuma/pkg/plugins/policies/core/generator.generator.Generate\n\tgithub.com/kumahq/kuma/pkg/plugins/policies/core/generator/generator.go:23\ngithub.com/kumahq/kuma/pkg/xds/generator/egress.Generator.Generate\n\tgithub.com/kumahq/kuma/pkg/xds/generator/egress/generator.go:108\ngithub.com/kumahq/kuma/pkg/xds/generator/core.CompositeResourceGenerator.Generate\n\tgithub.com/kumahq/kuma/pkg/xds/generator/core/resource_generator.go:22\ngithub.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateProfileSource).Generate\n\tgithub.com/kumahq/kuma/pkg/xds/generator/proxy_template.go:76\ngithub.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateGenerator).Generate\n\tgithub.com/kumahq/kuma/pkg/xds/generator/proxy_template.go:28\ngithub.com/kumahq/kuma/pkg/xds/server/v3.(*TemplateSnapshotGenerator).GenerateSnapshot\n\tgithub.com/kumahq/kuma/pkg/xds/server/v3/reconcile.go:167\ngithub.com/kumahq/kuma/pkg/xds/server/v3.(*reconciler).Reconcile\n\tgithub.com/kumahq/kuma/pkg/xds/server/v3/reconcile.go:55\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncEgress\n\tgithub.com/kumahq/kuma/pkg/xds/sync/dataplane_watchdog.go:290\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).Sync\n\tgithub.com/kumahq/kuma/pkg/xds/sync/dataplane_watchdog.go:84\ngithub.com/kumahq/kuma/pkg/xds/sync.(*dataplaneWatchdogFactory).New.func2\n\tgithub.com/kumahq/kuma/pkg/xds/sync/dataplane_watchdog_factory.go:43\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick\n\tgithub.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:70\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start\n\tgithub.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:40\ngithub.com/kumahq/kuma/pkg/xds/server/callbacks.(*dataplaneSyncTracker).OnProxyConnected.func2\n\tgithub.com/kumahq/kuma/pkg/xds/server/callbacks/dataplane_sync_tracker.go:60\nruntime.goexit\n\truntime/asm_arm64.s:1223"}
```

### PR DESCRIPTION
**Pull request by Icarus9913**
## Motivation

Once the egress is enabled, we should skip configuring endpoints for different mesh clusters. Because we don't support cross mesh in egress.

## Supporting documentation

Fix #14109

### CODE REVIEW

File: pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go [hunk 1]
```diff
@@ -1016,6 +1016,59 @@ var _ = Describe("MeshLoadBalancingStrategy", func() {
 				).
 				Build(),
 		}),
+		Entry("locality_aware_cross_zone_cross_mesh_egress_enabled", testCase{
+			resources: []core_xds.Resource{
```
Comment (Icarus9913) [inline pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go:1020]: @Automaat I'm not sure if the title is clear by using "cross mesh"

Comment (Automaat) [reply pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go:1020]: I think it is fine

**Review by Automaat — APPROVED** [review]
