### PR TITLE
test(e2e/ratelimit): fix rate limit check

### LINKED ISSUE #3874: Fix flaky RateLimit tests and reenable them
### Description

The RateLimit tests on Universal were disabled with https://github.com/kumahq/kuma/pull/3871 because of the flakiness of the way we check whether the RateLimit is enforced. We should investigate how to test the RateLimit in a non-flaky way and then reenable these tests.

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Summary

Rework the check for rate limiting and remove flakiness

Closes #3874

### CODE REVIEW

File: test/e2e/ratelimit/ratelimit_universal.go [hunk 1]
```diff
@@ -160,34 +181,30 @@ destinations:
 conf:
   http:
     requests: 1
-    interval: 10s
-`
+    interval: %[1]s
```
Comment (lahabana) [inline test/e2e/ratelimit/ratelimit_universal.go:184]: Why is the format different here?

File: test/e2e/ratelimit/ratelimit_universal.go [hunk 2]
```diff
@@ -67,43 +73,62 @@ var _ = E2EBeforeSuite(func() {
...
+	// Otherwise the bucket empties before we've sent all which will lead to the
+	// number of successes being more than the limit.
+	// So we send requests until the rate limit is first hit, send failing
+	// requests until the first one succeeds, then we send as
+	// many requests as we can until we are rate limited again.
+	// We compare that number of successes to the expected number.
+	// The assumption here is that we can send enough requests to hit the limit
+	// within the interval.
+	verifyRateLimit := func(client string, svc string, expected int) {
+		verifyError := fmt.Sprintf("couldn't verify rate limit for %s to %s to equal %d", client, svc, expected)
```
Comment (lahabana) [inline test/e2e/ratelimit/ratelimit_universal.go:87]: verifyErrorMsg would easier to understand also it might help readability if this is defined in the `verify` function

File: test/e2e/ratelimit/ratelimit_universal.go [hunk 3]
```diff
@@ -67,43 +73,62 @@ var _ = E2EBeforeSuite(func() {
...
-	verifyRateLimitExternal := func(client string, total int) func() int {
-		return func() int {
-			succeeded := 0
-			for i := 0; i < total; i++ {
-				_, _, err := cluster.Exec("", "", client, "curl", "-v", "--fail", "external-service.mesh")
-				if err == nil {
-					succeeded++
-				}
-			}
+		const verifyTimeout = 30 * time.Second
```
Comment (lahabana) [inline test/e2e/ratelimit/ratelimit_universal.go:118]: Maybe express this as `3 * limitInterval`

**Review by lahabana — APPROVED** [review]

File: test/e2e/ratelimit/ratelimit_universal.go (hunk 3 above)
Comment (michaelbeaumont) [reply test/e2e/ratelimit/ratelimit_universal.go:118]: So this timeout interval interface kind of bothers me. The interval is an overall limit on the `Eventually` call IIUC, we don't know how long each try takes, plus the poll interval in between. It's not really related to `limitInterval`. What I actually want is a limit on the number of attempts.

File: test/e2e/ratelimit/ratelimit_universal.go (hunk 1 above)
Comment (michaelbeaumont) [reply test/e2e/ratelimit/ratelimit_universal.go:184]: it's the format for reusing one of the `Sprintf` arguments
