### PR TITLE
fix(HostnameGenerator): consistently order resources

### LINKED ISSUE #10989: HostnameGenerator is flaky when there are collisions
### What happened?

1. Force HostnameGenerator to have collisions
2. Observe the hostname in `meshservice.status` is constantly changing from the real hostname to the error message 

We noticed this in the multizone scenario with statefulsets, but the repro could be way simpler:
1. Apply statefulset in 2 zones:
    ```yaml
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: redis
      namespace: kuma-demo
    spec:
      selector:
        matchLabels:
          app: redis
      serviceName: redis
      replicas: 0
      template:
        metadata:
          labels:
            app: redis
        spec:
          containers:
            - name: redis
              image: "redis"
              ports:
                - name: tcp
                  containerPort: 6379
              env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              lifecycle:
                preStop: # delay shutdown to support graceful mesh leave
                  exec:
                    command: ["/bin/sleep", "30"]
                postStart:
                  exec:
                    command: ["sh", "-c", "/usr/local/bin/redis-cli set zone ${POD_NAME}"]
    ```
2. In one zone apply the hostname generator (without `kuma.io/origin` label):
    ```yaml
    kind: HostnameGenerator
    apiVersion: kuma.io/v1alpha1
    metadata:
      name: local-headless-kube-mesh-service
      namespace: kuma-system
      labels:
        kuma.io/origin: zone
    spec:
      template: '{{ label "statefulset.kubernetes.io/pod-name" }}.{{ label "k8s.kuma.io/service-name" }}.{{ .Namespace }}.svc.mesh.local'
      selector:
        meshService:
          matchLabels:
            kuma.io/managed-by: k8s-controller
            k8s.kuma.io/is-headless-service: "true"
    ```
3. Observe hostnames appearing and disappearing 
image
4. Zone CP is constantly reconciling resources [zone-cp.log](https://github.com/user-attachments/files/16390351/zone-cp.log)

### PR DESCRIPTION
**Pull request by michaelbeaumont**
- https://github.com/kumahq/kuma/pull/11009

We weren't sorting the resources before running the HostnameGenerators

### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues -- Closes #10989 
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

File: pkg/core/resources/apis/meshservice/hostname/generator_test.go [hunk 1]
```diff
@@ -143,19 +152,114 @@ var _ = Describe("MeshService Hostname Generator", func() {
...
+						Status: kube_meta.ConditionTrue,
+						Reason: hostnamegenerator_api.GeneratedReason,
+					}},
+				},
+			))
+		}, "2s", "100ms").Should(Succeed())
+
+		// when
+		Expect(resManager.DeleteAll(context.Background(), &meshservice_api.MeshServiceResourceList{}, core_store.DeleteAllByMesh(model.DefaultMesh))).To(Succeed())
+		Expect(resManager.DeleteAll(context.Background(), &hostnamegenerator_api.HostnameGeneratorResourceList{})).To(Succeed())
```
Comment (jakubdyszkiewicz) [inline pkg/core/resources/apis/meshservice/hostname/generator_test.go:208]: Everything from this line looks like the rest of the test aside of the order of how we create other and backend.

Wouldn't this be enough to just keep
```
		Expect(other.Create(resManager, core_store.CreatedAt(createdSecond))).To(Succeed())
		Expect(backend.Create(resManager, core_store.CreatedAt(createdFirst))).To(Succeed())
```
?

This way we check that
1) we preserve the order, otherwise the test will be flaky
2) we respect the CreatedAt

File: pkg/core/resources/apis/meshservice/hostname/generator_test.go [hunk 2]
```diff
@@ -24,12 +24,14 @@ import (
 
 var _ = Describe("MeshService Hostname Generator", func() {
 	var stopChSend chan<- struct{}
+	var store core_store.ResourceStore
```
Comment (jakubdyszkiewicz) [inline pkg/core/resources/apis/meshservice/hostname/generator_test.go:27]: nit: do we need it?

File: pkg/core/resources/apis/meshservice/hostname/generator_test.go (hunk 1 above)
Comment (jakubdyszkiewicz) [reply pkg/core/resources/apis/meshservice/hostname/generator_test.go:208]: We also could keep the hostname generators in before each I think?

File: pkg/core/resources/apis/meshservice/hostname/generator_test.go (hunk 2 above)
Comment (michaelbeaumont) [reply pkg/core/resources/apis/meshservice/hostname/generator_test.go:27]: Ah no, I had this from when I tried with `memory.ClearStore`

File: pkg/core/resources/apis/meshservice/hostname/generator_test.go (hunk 1 above)
Comment (michaelbeaumont) [reply pkg/core/resources/apis/meshservice/hostname/generator_test.go:209]: > Everything from this line looks like the rest of the test aside of the order of how we create other and backend.

that's the point I think. that the order doesn't affect the outcome, even if `List` returns the resources in a different order

Comment (michaelbeaumont) [reply pkg/core/resources/apis/meshservice/hostname/generator_test.go]: > We also could keep the hostname generators in before each I think?

yeah, I added this back.
