### PR TITLE
fix(zone-egress): resolve zone-ingress advertized address

### LINKED ISSUE #4218: Not able to setup multizone cluster communication
### What happened?

Environment: kuma:1.5.x

Helm installation parameters in zone1- similarly for zone2 and global cp has also been installed with helm:
```
helm install kuma \
--namespace kuma-system \
--set controlPlane.mode=zone \
--set controlPlane.zone=zone1 \
--set ingress.enabled=true \
--set egress.enabled=true \
--set experimental.meshGateway=true \
--set cni.enabled=true \
--set cni.chained=true \
--set cni.netDir=/etc/cni/net.d \
--set cni.binDir=/opt/cni/bin \
--set cni.confName=10-calico.conflist \
--set cni.logLevel=info \
--set controlPlane.kdsGlobalAddress=grpcs://xx.xxx.xxx.xx:5685 \
--set controlPlane.logLevel=info kuma/kuma
```

Hi everyone. i am new to Kuma. I am getting some kind of issue when setting up multi-cluster deployment with 2 zones (e.g. zone1, zone2)

I can see that my kuma-egress-xxx pod logs in zone1 is showing some error:
```
[2022-04-26 06:48:07.489][20][warning][config] [source/common/config/grpc_subscription_impl.cc:126] gRPC config for type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment rejected: malformed IP address: xxx.region.elb.amazonaws.com. Consider setting resolver_name or setting cluster type to 'STRICT_DNS' or 'LOGICAL_DNS'
```
I am not able to successfully make connection across from zone1 to zone2.
I tried to do some curl from one of the kuma-sidecar enabled pod in zone1 to test the respective services hosted in zone2 and I am getting connection reset:
```
/ $ curl http://helloworld_kuma-demo_svc_5000.mesh/hello -vvv
*  Trying 240.0.0.9:80...
* Connected to helloworld_kuma-demo_svc_5000.mesh (240.0.0.9) port 80 (#0)
> GET /hello HTTP/1.1
> Host: helloworld_kuma-demo_svc_5000.mesh
> User-Agent: curl/7.82.0-DEV
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

I have make sure that all the firewall connection has been open as I managed to reach the target zone (e.g. zone2) ingress successfully using telnet:
```
/ $ curl -v telnet://xxx.region.elb.amazonaws.com:10001
*  Trying 122.248.xxx.xxx:10001...
* Connected to xxx.region.elb.amazonaws.com (122.248.xxx.xxx) port 10001 (#0)
```
I have also make sure the helloworld deployment in zone2 has been deployed successfully and with sidecar enabled

The global controlplane dataplanes also have successfully populated service entries from zone1 and zone2

How do I fix this issue on : Consider setting resolver_name or setting cluster type to 'STRICT_DNS' or 'LOGICAL_DNS'

### PR DESCRIPTION
**Pull request by lahabana**
### Summary

We were not resolving the address which was causing to send an invalid envoy config
as EDS can't accept hostnames.

Also refactor the topology/dataplanes to avoid redundant code and remove unecessary calls
when the ip already resolved

### Issues resolved

Fix #4218

### Testing

- [x] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes

### Backwards compatibility

- ~~[ ] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to take when upgrading.~~
- ~~[ ] Add `backport-to-stable` label if the code follows our [backporting policy](/CONTRIBUTING.md#backporting)~~

### CODE REVIEW

File: pkg/xds/topology/dataplanes_test.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ var _ = Describe("Resolve Dataplane address", func() {
 		if s == "advertise-2.example.com" {
 			return []net.IP{net.ParseIP("192.0.2.2")}, nil
 		}
-		return nil, errors.New("can't resolve host name")
+		return nil, errors.New("can't resolve host name:" + s)
```
Comment (lobkovilya) [inline pkg/xds/topology/dataplanes_test.go:36]: nit: no space after colon `errors.Errorf("can't resolve host name: %s", s)`

File: pkg/xds/topology/dataplanes.go [hunk 2]
```diff
@@ -69,19 +45,13 @@ func ResolveAddress(lookupIPFunc lookup.LookupIPFunc, dataplane *core_mesh.Datap
 }
 
 func ResolveZoneIngressPublicAddress(lookupIPFunc lookup.LookupIPFunc, zoneIngress *core_mesh.ZoneIngressResource) (*core_mesh.ZoneIngressResource, error) {
-	if zoneIngress.Spec.GetNetworking().GetAdvertisedAddress() == "" { // Ingress may not have public address yet.
-		return zoneIngress, nil
-	}
-	ips, err := lookupIPFunc(zoneIngress.Spec.GetNetworking().GetAdvertisedAddress())
+	res, err := lookupFirstIp(lookupIPFunc, zoneIngress.Spec.GetNetworking().GetAdvertisedAddress())
```
Comment (lobkovilya) [inline pkg/xds/topology/dataplanes.go:48]: nit: `ip` is better than `res`
