### PR TITLE
fix(policies): use GatewayAPI style header modifier in all policies

### LINKED ISSUE #5712: MeshHealthCheck and MeshRateLimit headers to add/set should have the same format as GatewayAPI
### Description

this is required for coherency

### PR DESCRIPTION
**Pull request by lahabana**
MeshHealthCheck and MeshRateLimit didn't adopt the same style of headers.

Update MeshRetry to ensure Pascal case for Type value and add Present and Absent as types.

This is important for api coherency.

Fix #5712

Signed-off-by: Charly Molter <charly.molter@konghq.com>

### Checklist prior to review

- [x] Link to docs PR or issue --
- [x] Link to UI issue or PR --
- [x] Is the [issue worked on linked][1]? --
- [x] The PR does not hardcode values that might break projects that depend on kuma (e.g. "kumahq" as a image registry) --
- [x] The PR will work for both Linux and Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Unit Tests --
- [x] E2E Tests --
- [x] Manual Universal Tests --
- [x] Manual Kubernetes Tests --
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [x] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

File: pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go [hunk 1]
```diff
@@ -188,14 +191,15 @@ healthChecks:
     path: /health
     requestHeadersToAdd:
       - header:
-          key: x-kuma-tags
+          key: X-Kuma-Tags
```
Comment (jakubdyszkiewicz) [inline pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go:194]: I'm pretty sure this should be lower case. I think I would even add a validation to the base type to only accept lowercase headers.

Envoy lowercase headers by default (because of HTTP/2) and there were many problems with that. I would stick to lower case to avoid this altogether.

Comment (lahabana) [reply pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go:194]: I'd love to get @michaelbeaumont 's opinion here because I've been adding `http.CanonicalHeaderKey()` following his example.

Comment (michaelbeaumont) [reply pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go:194]: Ah I took this from the gateway plugin code.

Comment (lahabana) [reply pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go]: Going for lower case only allowed. Main reason is that it's easier to extend later than to restrict

**Comment by lahabana** [comment]
@jakubdyszkiewicz updated with lower case headers

**Review by jakubdyszkiewicz — APPROVED** [review]
looks good, thanks
