### PR TITLE
fix(*) traffic logging to tcp backends

### LINKED ISSUE #853: Kuma-sidecar not starting when using Telepresence
### Summary

Telepresence is a really useful tool than allows you to substitute a pod in your kubernetes cluster by a docker image on your local computer. This image helps to understand how it works: 

1_ceyHmoGefCl-EuWleiZFQw
_Image modified from [medium](https://medium.com/swlh/local-development-with-telepresence-256911cb21e9)_

I am using this tool during development to test my new app version directly in the kubernetes cluster (I don't need to have a local test cluster).

The problem is that when I use telepresence to replace one of my pods the kuma-sidecar is not starting alongside the pods set by telepresence in replacement of my normal pod. 
Here are the logs of the kuma-sidecar:

```
2020-06-25T07:07:20.421Z	INFO	Skipping reading config from file
2020-06-25T07:07:20.421Z	INFO	kuma-dp.run	effective configuration	{"config": "controlPlane:\n  apiServer:\n    url: http://kuma-control-plane.kuma-system:5681\ndataplane:\n  mesh: default\n  name: app-dn-deployment-5ab90d93b67a4f72be34651114fd7de4-67679bbrtq74.datanostrum\n  drainTime: 30s\ndataplaneRuntime:\n  binaryPath: envoy\n  dataplaneTokenPath: /var/run/secrets/kubernetes.io/serviceaccount/token\n"}
2020-06-25T07:07:20.425Z	INFO	kuma-dp.run	picked a free port for Envoy Admin API to listen on	{"port": "9901"}
2020-06-25T07:07:20.425Z	INFO	kuma-dp.run	generated Envoy configuration will be stored in a temporary directory	{"dir": "/tmp/kuma-dp-553564296"}
2020-06-25T07:07:20.425Z	INFO	kuma-dp.run	starting Kuma DP	{"version": "0.5.1"}
2020-06-25T07:07:20.426Z	ERROR	kuma-dp.run	error while running Kuma DP	{"error": "listen unix /tmp/kuma-access-logs-app-dn-deployment-5ab90d93b67a4f72be34651114fd7de4-67679bbrtq74.datanostrum-default.sock: bind: invalid argument"}
Error: listen unix /tmp/kuma-access-logs-app-dn-deployment-5ab90d93b67a4f72be34651114fd7de4-67679bbrtq74.datanostrum-default.sock: bind: invalid argument
```` 

### Steps To Reproduce

1. With telepresence installed locally and un pod in your kubernetes cluster.
2. Run a command similar to:
```
telepresence --swap-deployment app-dn-deployment --namespace myNameSpace --docker-run --rm -p 5005:5005 app-dn:latest
```
3. Use kubectl to see that the kuma-sidecar is not starting and to see the logs
```
kubectl get pods -n myNameSpace
kubectl logs app-dn-deployment-5ab90d93b67a4f72be34651114fd7de4-67679bbrtq74 kuma-sidecar -n myNameSpace
```

### Additional Details & Logs

- Kubernetes version: 1.7.5-1
- Kuma version: 0.5.1
- Telepresence version: 0.105

### PR DESCRIPTION
**Pull request by nickolaev**
### Summary

#894 actually broke TrafficLogs with TCP logger. It actually created a discrepancy in the naming of the UNIX socket between `kuma-dp` and the bootstrap generator in `kuma-cp`. In effect, Envoy was not able to find the GRPC logging service as provided by `kuma-dp` and the logs are never sent to the TCP logger.

Revert it and shorten the UNIX socket name by removing the not needed prefix `kuma-access-logs-`.

### Issues resolved

Fix #853 (again)

### Documentation

- Not needed

### CODE REVIEW

File: pkg/xds/bootstrap/generator.go [hunk 1]
```diff
@@ -183,7 +183,7 @@ func (b *bootstrapGenerator) generateFor(proxyId core_xds.ProxyId, dataplane *co
 		}
 		certBytes = base64.StdEncoding.EncodeToString(cert)
 	}
-	accessLogPipe := fmt.Sprintf("/tmp/kuma-access-logs-%s-%s.sock", request.Name, request.Mesh)
+	accessLogPipe := fmt.Sprintf("/tmp/%s-%s.sock", request.Name, request.Mesh)
```
Comment (lobkovilya) [inline pkg/xds/bootstrap/generator.go:186]: Maybe it's better to create a function like: 
```go
func AccessLogPipeName(name, mesh string) string {
    return fmt.Sprintf("/tmp/%s-%s.sock", name, mesh)
}
```
and use it from both places? That'd allow avoiding bugs like this one, what do you think?

**Comment by jakubdyszkiewicz** [comment]
IMHO this does not solve the initial problem.

The problem was that if the name has more than 108 characters, it will fail. Even with getting rid of the `kuma-access-logs-` we can still easily hit the limit because the name can have up to 253 chars https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#:~:text=This%20means%20the%20name%20must,no%20more%20than%20253%20characters

On top of that, I think it makes sense to mark this file that it is kuma access log socket, otherwise someone can just delete it.
My suggestion is to construct this `kuma-al-{name}-{mesh}` and trim this to 100 characters.

**Review by jakubdyszkiewicz — APPROVED** [review]
