### PR TITLE
fix(kuma-cp): use contexts instead of channels in watchdog

### LINKED ISSUE #7349: SimpleWatchdog.Start should take a ctx
### Description

After working on:
 - https://github.com/kumahq/kuma/pull/7348

We realised that SimpleWatchdog takes in a channel it would probably just use a context as it would avoid needing a goroutine and complex logic to handle closed channel.
If we actually go up the levels we can see that go-control-plane passes the ctx of the stream already. Should we just use this one or would that cause issues?
We have the stream ctx stored already in dataplane_callbacks.

### PR DESCRIPTION
**Pull request by lahabana**
This makes the code simpler and easier to track

xref #11094
fix #7349

### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues --
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by michaelbeaumont** [comment]
I think you want to link https://github.com/kumahq/kuma/issues/7349

File: pkg/util/watchdog/watchdog.go [hunk 1]
```diff
@@ -7,66 +7,42 @@ import (
...
-		case <-stop:
+		case <-ctx.Done():
 			if w.OnStop != nil {
 				w.OnStop()
 			}
-			// cancel will be called by the above goroutine
 			return
 		}
 	}
 }
```
Comment (Icarus9913) [inline pkg/util/watchdog/watchdog.go:36]: Nice clean up with the goroutines generation in every loop!

File: pkg/util/watchdog/watchdog.go [hunk 2]
```diff
@@ -7,66 +7,42 @@ import (
...
 		select {
 		case <-ticker.C:
-			continue
-		case <-stop:
+		case <-ctx.Done():
 			if w.OnStop != nil {
 				w.OnStop()
 			}
-			// cancel will be called by the above goroutine
 			return
```
Comment (Icarus9913) [inline pkg/util/watchdog/watchdog.go:33]: Just one consideration here:
The golang select runs in random rather than rust marco `select!`, if the `ticker.C` and `ctx.Done` occurred at the same time, it might goes into `<-ticker.C` and runs the for loop again. You can add another `ctx.Done` check inner the `ticker.C` but it looks ugly.

I would prefer to make it in order with priority just like this:
```text
select {
  case <-ctx.Done():
    if w.OnStop != nil {
	    w.OnStop()
    }
    return
  default:
}

select {
  case <-ticker.C:
}
```

If there's something wrong with this, please point it out.

Comment (lahabana) [reply pkg/util/watchdog/watchdog.go:33]: Correct. It's a little trickier as you still need to select on the ctx in the second select but I'll improve a bit.

Comment (lahabana) [reply pkg/util/watchdog/watchdog.go]: PTAL @Icarus9913

Comment (Icarus9913) [reply pkg/util/watchdog/watchdog.go]: The new one looks good to me.

**Review by michaelbeaumont — COMMENTED** [review]
This kind of mixes a refactor and some fixes, right?

File: pkg/kds/v2/server/components.go [hunk 3]
```diff
@@ -128,7 +127,7 @@ func newSyncTracker(
 			NewTicker: func() *time.Ticker {
 				return time.NewTicker(refresh)
 			},
-			OnTick: func(context.Context) error {
+			OnTick: func(ctx context.Context) error {
```
[the remark this answers is not in the document]
Comment (lahabana) [reply pkg/kds/v2/server/components.go:130]: it's actually the same ctx now so I thought it was just clearer this way. Also in any case the ctx for reconcile should be the one of the OnTick

[the remark this answers is not in the document]
Comment (michaelbeaumont) [reply pkg/kds/v2/server/components.go:130]: do we still need the outer one?

**Review by michaelbeaumont — APPROVED** [review]
