### PR TITLE
fix(kuma-cp) switch to mTLS when CP communicates with Envoy Admin

### LINKED ISSUE #1534: Security of accessing Envoy's Admin API from the Control Plane
### Summary

Recently, we introduced a way for the Control Plane to communicate with Envoy's Admin API.
We needed that to support Jobs on Kubernetes (we force shutdown of Envoy `/quitquitquit` when all other containers are down in a Job's Pod). Obviously, Envoy Admin is sensitive (you can bring down whole environment if you have access to all Envoy admins) and cannot be exposed to the outside world.

Additionally, in the future, I think we will reuse this capability for a couple of use cases like:
* Scraping metrics to build service map
* Provide better debug tools (like accessing config of Envoy using just Kuma GUI / kumactl)

The security mechanism that was picked is:
* Secure the connection with a self-signed TLS cert kept in memory (we cannot reuse mesh CA, because the feature has to work regardless if mTLS is on), just to have TLS so the traffic cannot be listened to.
* Authenticate CP in the Dataplane by generating a Token which is HMAC of "name.mesh" signed with SHA256 key. For this, we need to generate and keep a signing key in the control plane, but not token themselves.

Although this approach works, it has 2 downsides:
* Token is visible in Envoy's `/config_dump`. We will have to be very careful to not expose this to the users when we provide debug tools.
* Since self-signed TLS cert is kept in the memory (not synced between instances), we are not verifying TLS connection to the data plane, which is prone to MITM attack.

The alternative approach is to do a proper mTLS, meaning:
* Instead of generating signing key, generate a CA
* Instead of generating token, for every Envoy generate a cert+key with their identity in the SAN (IP address)
* On Envoy side, instead of verifying header with token, verify that the client cert has a cert signed with a CA and has proper SAN
* On Control Plane side, check if Envoy to which we are connecting to has a cert signed by proper CA and has expected IP in SAN

This way, we don't expose credentials in `/config_dump` and we are verifying that we are connecting to a proper Envoy.

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**
#### Context

Some time ago, we had a problem with Jobs on Kubernetes. The job is considered done only when all containers exit. Kuma DP never exits on its own, so jobs were stuck in a running state. To fix this problem, we added a controller that tracks jobs and sends `/quitquitquit` to Envoy when all other containers are done. This way the job was finished properly.

Of course, we could not just expose `/quitquitquit` to the world, therefore we secured this communication.
The security that we introduced was that communication was protected by TLS with an autogenerated self-signed cert that was only kept in memory, so the CP could not verify DP identity.
As for authentication, we autogenerated RSA signing key called (envoy-admin-client-token). Then we constructed a value (token) of signing key and dp name using HMAC and require this value as a header when CP is communicating with Envoy.

#### Problem

This approach is not great because
1) It's prone to the MITM attack. We cannot skip TLS verification and send sensitive data on the same connection. A malicious actor could proxy the traffic, expose whatever cert they want since we are not verifying it, accept the request and acquire token. Then the actor could operate Envoy Admin API.
2) Required token is visible in config dump.

On top of that, due to a mistake of both author and reviewers, we also used DP token signing key instead of Envoy Admin Client Token. See https://github.com/kumahq/kuma/pull/1650/files

In practice, MITM attack would be not easy to perform because it requires tricking CP that DP has a different IP than expected. If someone has the power to do so, they can probably do more damage than this. This does not change the fact that we should fix those issues.

#### Solution

One of the solution would be to generate CA. Then, using this CA we could
* generate tls pairs to protect each individual DP server, so CP can verify that it connects to the right destination
* generate client certs so DPs could verify the CP

The problem with this approach is that we are introducing yet another CA and certs that we need to explain to users.
The CA needs to be managed.
The amount of certs, CAs, tokens is already difficult to understand.

The alternative solution that is implemented with this PR is that
* When mTLS on the mesh is enabled, we use just a regular DP cert to protect Admin API, so CP can verify that it's connecting to the proper DP. This solves the first problem.
* When mTLS on the mesh is disabled, we stick to autogenerated in-memory self-signed cert. In this case, CP cannot verify that it's connecting to the proper DP, BUT we are not sending sensitive information on this connection because...
* Instead of sending token as header, we use client certs. DP already verifies the CP cert on start (if not on bootstrap, then on XDS), we present the very same certificates when we are initiating connection from CP to DP, so DP is sure that it is CP that is accessing Admin API. This solves the second problem.

### Full changelog

* Remove Envoy Admin Client Signing Key
* Move ADS TLS validation context to static secret so it can be reused for Admin API TLS endpoints validation.
* Move jobs tests from multizone to single-zone and check both with mTLS enabled and disabled.

### Issues resolved

Fix #1534

### Documentation

- [X] No docs, internal changes.

### Testing

- [X] Unit tests
- [X] E2E tests
- [X] Manual testing on Universal
- [ ] Manual testing on Kubernetes 

### Backwards compatibility

- [X] It's backward compatible with a note that during upgrade (new CP, old DP), the CP cannot access the TLS endpoints of admin. It should be ok because the only use case when we are trying to access TLS endpoints is a termination of the job. It's unlikely to have new CP and old DP in the jobs because jobs do not usually live long. Even if that will be the case, a user can just manually delete the job this time.

### CODE REVIEW

File: pkg/envoy/admin/client.go [hunk 1]
```diff
@@ -1,116 +1,166 @@
...
 	// in the DataplaneInsights.
-	portUint := a.cfg.Runtime.Kubernetes.Injector.SidecarContainer.AdminPort
-
-	return net.JoinHostPort(ip, strconv.FormatUint(uint64(portUint), 10))
+	return net.JoinHostPort(ip, strconv.FormatUint(uint64(a.adminPort), 10))
 }
 
 func (a *envoyAdminClient) PostQuit(dataplane *core_mesh.DataplaneResource) error {
-	token, err := a.GenerateAPIToken(dataplane)
+	httpClient, err := a.buildHTTPClient(dataplane)
```
Comment (lobkovilya) [inline pkg/envoy/admin/client.go:148]: Why it's preferable to build httpClient per request? Were there any problems with old approach when httpClient was built in constructor

**Review by lobkovilya — APPROVED** [review]

File: pkg/envoy/admin/client.go (hunk 1 above)
Comment (jakubdyszkiewicz) [reply pkg/envoy/admin/client.go:148]: It's not preferable but we need to set CA of the Mesh-based on the dataplane.

**Review by bartsmykla — APPROVED** [review]
lgtm
