### PR TITLE
fix(policy): matcher with same key not the same value

### LINKED ISSUE #6426: Merging of policies results in not applying policy on some outbound
### What happened?

Reported by Brent Yarger. Apparently when applied this policy
```
apiVersion: kuma.io/v1alpha1
kind: MeshRetry
metadata:
  name: retry-all
  namespace: kong-mesh-system
  labels:
    kuma.io/mesh: default 
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: Mesh
      default:
        http:
          numRetries: 1
          backOff:
            baseInterval: 5s
            maxInterval: 1m
          retryOn:
            - "5xx"
```
and
```
apiVersion: kuma.io/v1alpha1
kind: MeshRetry
metadata:
  name: retry-echo-to-mockserver
  namespace: kong-mesh-system
  labels:
    kuma.io/mesh: default # optional, defaults to `default` if unset
spec:
  targetRef:
    kind: MeshService
    name: echo-service_default_svc_8080
  to:
    - targetRef:
        kind: MeshService
        name: mockserver_mockserver_svc_1080
      default:
        http:
          numRetries: 5
          backOff:
            baseInterval: 10s
          retryOn:
            - "5xx"
```
results in the other upstreams in the echo service sidecar get retry config removed.

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**
Fix #6426

### Checklist prior to review

- [X] [Link to relevant issue][1] as well as docs and UI issues --
- [X] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [X] Tests (Unit test, E2E tests, manual test on universal and k8s) --
- [X] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [X] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [X] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Comment by jakubdyszkiewicz** [comment]
@mergifyio backport release-2.1 release-2.0

File: pkg/core/xds/rules.go [hunk 1]
```diff
@@ -39,7 +39,7 @@ func (ss Subset) IsSubset(other Subset) bool {
 			if otherTag.Value == tag.Value && otherTag.Not != tag.Not {
 				return false
 			}
-			if otherTag.Value != tag.Value && !otherTag.Not {
+			if otherTag.Value != tag.Value && otherTag.Not == tag.Not {
```
Comment (lobkovilya) [inline pkg/core/xds/rules.go:42]: It works for us because `otherTag.Not` is always `false` (we don't allow "not" in policies, only in rules). But in general, I think it's still an incorrect condition:
```
other:
  key1: !value1
---
tag:
  key1: !value2
```
by looking at `key1` we can't say for sure if `other` is (or isn't) a subset of `tag`. 

So probably the condition should be:
```go
if otherTag.Value == tag.Value && otherTag.Not != tag.Not {
	return false
}
if otherTag.Value != tag.Value && !otherTag.Not && !tag.Not {
	return false
}
```

Comment (jakubdyszkiewicz) [reply pkg/core/xds/rules.go]: Ok, make sense. Changed.

**Review by lukidzi — APPROVED** [review]

**Review by lobkovilya — APPROVED** [review]
