### PR TITLE
fix(gateway): run validating webhook on MeshGatewayInstance

### LINKED ISSUE #10329: MeshGatewayInstance Validating Webhook not works
### What happened?

Refer to the PR [rename Gateway to MeshGateway](https://github.com/kumahq/kuma/pull/3799), we changed the `Gateway` to `MeshGateway` but lacked of changing the k8s ValidatingWebhookConfiguration:
https://github.com/kumahq/kuma/blob/413bddfb40f22f3c2f2a52deef78d13be3c6a3c0/deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml#L235

### PR DESCRIPTION
**Pull request by Icarus9913**
Refer to #3799, we missed the change of the ValidatingWebhookConfiguration. Furthermore, with #9504 we deprecated kuma.io/service tag for the MeshGatewayInstance and we need to remove the tag validations.

close #10329 

### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues --
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

File: pkg/plugins/runtime/k8s/webhooks/gateway_instance_validator.go [hunk 1]
```diff
@@ -77,9 +77,7 @@ func (h *GatewayInstanceValidator) ValidateUpdate(ctx context.Context, req admis
 func (h *GatewayInstanceValidator) validateTags(gatewayInstance *mesh_k8s.MeshGatewayInstance) admission.Response {
 	tags := gatewayInstance.Spec.Tags
 
-	err := core_mesh.ValidateTags(validators.RootedAt("tags"), tags, core_mesh.ValidateTagsOpts{
-		RequireService: true,
-	})
+	err := core_mesh.ValidateTags(validators.RootedAt("tags"), tags, core_mesh.ValidateTagsOpts{})
 
 	if err.HasViolations() {
 		return convertValidationErrorOf(err, gatewayInstance, gatewayInstance.GetObjectMeta())
```
Comment (Icarus9913) [inline pkg/plugins/runtime/k8s/webhooks/gateway_instance_validator.go:83]: Actually, this function doesn't validate anything right now. Just keep it for the potential validations in the future.

**Comment by Icarus9913** [comment]
cc @michaelbeaumont @lukidzi

**Review by jakubdyszkiewicz — APPROVED** [review]

**Comment by jakubdyszkiewicz** [comment]
Merging for Icarus, because I think he does not have permissions yet
