### PR TITLE
fix(inspect): remove spec from inspect policy output

### LINKED ISSUE #5383: `kumactl inspect dataplane --type policies` panic
### What happened?

From master:

```
./build/artifacts-darwin-amd64/kumactl/kumactl inspect dataplane --type policies redis-1
panic: interface conversion: *v1alpha1.MeshAccessLog is not protoreflect.ProtoMessage: missing method ProtoReflect

goroutine 1 [running]:
github.com/kumahq/kuma/pkg/core/resources/model/rest/unversioned.(*Resource).UnmarshalJSON(0xc0002fa000, {0xc0002d28a9, 0x342, 0x757})
	/Users/cmolter/code/kuma/pkg/core/resources/model/rest/unversioned/resource.go:70 +0xc7
encoding/json.(*decodeState).object(0xc0007261b0, {0x305a8e0?, 0xc00051a0c0?, 0xb?})
	/usr/local/go/src/encoding/json/decode.go:612 +0x68a
encoding/json.(*decodeState).value(0xc0007261b0, {0x305a8e0?, 0xc00051a0c0?, 0x1?})
	/usr/local/go/src/encoding/json/decode.go:373 +0x45
encoding/json.(*decodeState).array(0xc0007261b0, {0x2dbb020?, 0xc000732180?, 0x18?})
	/usr/local/go/src/encoding/json/decode.go:561 +0x626
encoding/json.(*decodeState).value(0xc0007261b0, {0x2dbb020?, 0xc000732180?, 0x2f96c00?})
	/usr/local/go/src/encoding/json/decode.go:363 +0x7e
encoding/json.(*decodeState).object(0xc0007261b0, {0x2f96c00?, 0xc0007380b0?, 0x78f?})
	/usr/local/go/src/encoding/json/decode.go:774 +0xca5
encoding/json.(*decodeState).value(0xc0007261b0, {0x2f96c00?, 0xc0007380b0?, 0xf?})
	/usr/local/go/src/encoding/json/decode.go:373 +0x45
encoding/json.(*decodeState).object(0xc0007261b0, {0x2d95ca0?, 0xc00051a080?, 0xb?})
	/usr/local/go/src/encoding/json/decode.go:774 +0xca5
encoding/json.(*decodeState).value(0xc0007261b0, {0x2d95ca0?, 0xc00051a080?, 0x1?})
	/usr/local/go/src/encoding/json/decode.go:373 +0x45
encoding/json.(*decodeState).array(0xc0007261b0, {0x2dba660?, 0xc00051a028?, 0x7d7?})
	/usr/local/go/src/encoding/json/decode.go:561 +0x626
encoding/json.(*decodeState).value(0xc0007261b0, {0x2dba660?, 0xc00051a028?, 0x5?})
	/usr/local/go/src/encoding/json/decode.go:363 +0x7e
encoding/json.(*decodeState).object(0xc0007261b0, {0x2ed7060?, 0xc00051a020?, 0x0?})
	/usr/local/go/src/encoding/json/decode.go:774 +0xca5
encoding/json.(*decodeState).value(0xc0007261b0, {0x2ed7060?, 0xc00051a020?, 0x90?})
	/usr/local/go/src/encoding/json/decode.go:373 +0x45
encoding/json.(*decodeState).unmarshal(0xc0007261b0, {0x2ed7060?, 0xc00051a020?})
	/usr/local/go/src/encoding/json/decode.go:180 +0x1de
encoding/json.Unmarshal({0xc0002d2800, 0x656, 0x800}, {0x2ed7060, 0xc00051a020})
	/usr/local/go/src/encoding/json/decode.go:107 +0x125
github.com/kumahq/kuma/pkg/api-server/types.(*DataplaneInspectResponse).UnmarshalJSON(0xc000724000, {0xc0002d2800, 0x656, 0x800})
	/Users/cmolter/code/kuma/pkg/api-server/types/inspect.go:188 +0x197
encoding/json.(*decodeState).object(0xc000726000, {0x2d81b60?, 0xc000194020?, 0x0?})
	/usr/local/go/src/encoding/json/decode.go:612 +0x68a
encoding/json.(*decodeState).value(0xc000726000, {0x2d81b60?, 0xc000194020?, 0x90?})
	/usr/local/go/src/encoding/json/decode.go:373 +0x45
encoding/json.(*decodeState).unmarshal(0xc000726000, {0x2d81b60?, 0xc000194020?})
	/usr/local/go/src/encoding/json/decode.go:180 +0x1de
encoding/json.Unmarshal({0xc0002d2800, 0x657, 0x800}, {0x2d81b60, 0xc000194020})
	/usr/local/go/src/encoding/json/decode.go:107 +0x125
github.com/kumahq/kuma/app/kumactl/pkg/resources.(*httpDataplaneInspectClient).InspectPolicies(0xc000e02eb0, {0x383bd30, 0xc00019c008}, {0x33a9f37?, 0x383d310?}, {0x7ff7bfeff821, 0x7})
	/Users/cmolter/code/kuma/app/kumactl/pkg/resources/dataplane_inspect_client.go:49 +0x1c5
github.com/kumahq/kuma/app/kumactl/cmd/inspect.newInspectDataplaneCmd.func3(0x0?, {0xc000e002a0?, 0x0?, 0x0?})
	/Users/cmolter/code/kuma/app/kumactl/cmd/inspect/inspect_dataplane.go:87 +0x2e3
github.com/kumahq/kuma/app/kumactl/pkg/errors.FormatErrorWrapper.func1(0xc0006aa000?, {0xc000e002a0?, 0x3?, 0x3?})
	/Users/cmolter/code/kuma/app/kumactl/pkg/errors/formatter.go:14 +0x22
github.com/spf13/cobra.(*Command).execute(0xc0006aa000, {0xc000e00240, 0x3, 0x3})
	/Users/cmolter/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000071200)
	/Users/cmolter/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/cmolter/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/kumahq/kuma/app/kumactl/cmd.Execute()
	/Users/cmolter/code/kuma/app/kumactl/cmd/root.go:104 +0x1e
main.main()
	/Users/cmolter/code/kuma/app/kumactl/main.go:6 +0x17
```

### PR DESCRIPTION
**Pull request by lahabana**
It's redundant and makes the response very big.
It was also not very straight forward with new and old policy

While this is a breaking change, we strictly remove things which shouldn't be an issue (kumactl was already not showing this)

Fix #5383 

Signed-off-by: Charly Molter <charly.molter@konghq.com>

### Checklist prior to review

- [x] Link to docs PR or issue -- https://github.com/kumahq/kuma-website/pull/1171
- [x] Link to UI issue or PR --
- [x] Is the [issue worked on linked][1]? --
- [x] The PR does not hardcode values that might break projects that depend on kuma (e.g. "kumahq" as a image registry) --
- [x] The PR will work for both Linux and Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Unit Tests --
- [x] E2E Tests --
- [x] Manual Universal Tests --
- [x] Manual Kubernetes Tests --
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [x] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

File: pkg/api-server/inspect_endpoints.go [hunk 1]
```diff
@@ -313,7 +314,7 @@ func inspectPolicies(
 func routeDestinationToAPIDestination(des route.Destination) api_server_types.Destination {
 	policies := api_server_types.PolicyMap{}
 	for kind, p := range des.Policies {
-		policies[kind] = rest_unversioned.From.Resource(p)
+		policies[kind] = rest.From.Resource(p).GetMeta()
```
Comment (lobkovilya) [inline pkg/api-server/inspect_endpoints.go:317]: It seems like an unnecessary conversion of the whole resource and then taking `meta` from the converted result. I'd rather implement a method that converts only `meta`:
```go
func (f *from) ResourceMeta(r core_model.ResourceMeta) v1alpha1.ResourceMeta {
}
```
later we can use `rest.From.ResourceMeta()` inside `rest.From.Resource()`

Comment (lahabana) [reply pkg/api-server/inspect_endpoints.go:317]: Yes and no. ResourceMeta is not working great here because we need to type which is in the resource descriptor (this is why I introduced From.Meta that should be used here

File: pkg/api-server/types/inspect.go [hunk 2]
```diff
@@ -6,13 +6,13 @@ import (
...
 	core_model "github.com/kumahq/kuma/pkg/core/resources/model"
-	"github.com/kumahq/kuma/pkg/core/resources/model/rest/unversioned"
+	"github.com/kumahq/kuma/pkg/core/resources/model/rest/v1alpha1"
 )
 
 type AttachmentEntry struct {
 	Type    string `json:"type"`
 	Name    string `json:"name"`
-	Service string `json:"service"`
+	Service string `json:"service,omitempty"`
```
Comment (lobkovilya) [inline pkg/api-server/types/inspect.go:15]: Can `Name` also be marked as `omitempty`?
