### PR TITLE
fix: automatically detect dns lookup family for cp cluster

### LINKED ISSUE #2000: `ads_cluster` + `STRICT_DNS` tries to resolve IPV6 addr
### Summary

If the `ads_cluster` selects `STRICT_DNS`, it will try to resolve an IPV6 address every 5 seconds. This is because 
`dns_lookup_family` defaults to `AUTO` when unset and `AUTO` [tries IPV6 first](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#enum-config-cluster-v3-cluster-dnslookupfamily). 

If this occurs and the upstream server cannot resolve a lookup for an IPV6 address, there will be a `NXDomain` returned every 5 seconds due to `dns_failure_refresh_rate` \ `dns_refresh_rate`.

We should additionally set whether to use IPV4 / IPV6 for `dns_lookup_family`, much like is done for `StrictDNSClusterConfigurer`:

https://github.com/kumahq/kuma/blob/bd14216f56ffb63b3c071a89f45746d2da38d103/pkg/xds/envoy/clusters/v2/strict_dns_cluster_configurer.go#L19-L31

### Additional Details & Logs

- Version: Kuma 1.1.6
- Configuration: Universal
- Platform and Operating System: CentOS 7

### PR DESCRIPTION
**Pull request by slonka**
Signed-off-by: slonka <slonka@users.noreply.github.com>

### Summary

An alternative to #4264. Instead of allowing the user to configure DnsLooupFamily we run a query in kuma-dp and determine it ourselves.

### Full changelog

* Implement `dnsLookupFamilyFromXdsHost` which looks up `XdsHost` IPs and sets `DnsLooupFamily` accordingly

### Issues resolved

Fix #2000

### Documentation

- [X] No additional docs

### Testing

- [X] Unit tests
- [ ] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes

### Backwards compatibility

- [X] No breaking changes
- [X] doesn't meet backporting criteria

### CODE REVIEW

File: pkg/xds/bootstrap/template_v3.go [hunk 1]
```diff
@@ -295,6 +297,34 @@ func genConfig(parameters configParameters) (*envoy_bootstrap_v3.Bootstrap, erro
...
+			} else {
+				hasIPv6 = true
+			}
+		}
+
+		if hasIPv6 {
+			return envoy_cluster_v3.Cluster_AUTO
+		} else if hasIPv4 {
+			return envoy_cluster_v3.Cluster_V4_ONLY
+		}
```
Comment (lahabana) [inline pkg/xds/bootstrap/template_v3.go:322]: Nit: may it's more readable if you only look at whether there's a no v6 address (all other cases are Cluster_AUTO no?).

File: pkg/xds/bootstrap/export_template.go [hunk 2]
```diff
@@ -0,0 +1,5 @@
+package bootstrap
+
+var (
+	DnsLookupFamilyFromXdsHost = dnsLookupFamilyFromXdsHost
+)
```
Comment (lahabana) [inline pkg/xds/bootstrap/export_template.go:5]: This is not a pattern we've been following much atm. So I think it makes sense for @jakubdyszkiewicz to choose whether we let this through or not WRT code coherency :).

**Review by lahabana — APPROVED** [review]
LGTM thx for finding a way to get rid of the parameter

File: pkg/xds/bootstrap/template_v3.go (hunk 1 above)
Comment (slonka) [reply pkg/xds/bootstrap/template_v3.go:317]: simplified

File: pkg/xds/bootstrap/export_template.go (hunk 2 above)
Comment (slonka) [reply pkg/xds/bootstrap/export_template.go:5]: pinging @jakubdyszkiewicz, this is the approach that go std lib uses https://go.dev/src/net/http/export_test.go so I thought it's ok, happy to change it.

Comment (slonka) [reply pkg/xds/bootstrap/export_template.go]: You're right, I went with `2`

File: pkg/xds/bootstrap/template_v3_test.go [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+	It("should return AUTO when IPv6 found", func() {
+		// given
+		lookupFn := func(host string) ([]net.IP, error) {
+			return []net.IP{net.IPv6loopback}, nil
+		}
+
+		// when
+		result := dnsLookupFamilyFromXdsHost("example.com", lookupFn)
+
+		//
```
Comment (jakubdyszkiewicz) [inline pkg/xds/bootstrap/template_v3_test.go:22]: `// then`?

**Review by michaelbeaumont — APPROVED** [review]
LGTM

File: pkg/xds/bootstrap/template_v3_test.go [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+import (
+	"errors"
+	"net"
+
+	envoy_cluster_v3 "github.com/envoyproxy/go-control-plane/envoy/config/cluster/v3"
+	. "github.com/onsi/ginkgo/v2"
+	. "github.com/onsi/gomega"
+)
+
+var _ = Describe("dnsLookupFamilyFromXdsHost", func() {
```
Comment (jakubdyszkiewicz) [inline pkg/xds/bootstrap/template_v3_test.go:12]: nit: very often when we are doing same action with differnt input expecting differnt output, we use DescribeTable. Not saying you should rewrite this test, because I'm not sure if it make sense in this context. Just keep an eye on it.
