### PR TITLE
fix(kumactl) normalize generating TLS certificates

### LINKED ISSUE #3009: Normalize kumactl TLS certificate hostname options
### Summary

`kumactl generate tls-certificate` requires a `--cp-hostname` argument when generation server certificates, but you are not allowed to pass this when generating client certificates. I'd like to normalize the behavior so that

* there is a (required) `--hostname`argument in both cases (`--cp-hostname` can stay as a compatibility alias)
* the first hostname value should be the certificate subject CN
*  all the hostnames should be given as DNS alt names
* "localhost" isn't hardcoded as a DNS altname

This would mean "kuma" is no longer the subject CN for generated certificates.

I expect these changes to make the generated certificated more regular, and suitable for use as general-purpose self-signed TLS certificates.

### PR DESCRIPTION
**Pull request by jpeach**
### Summary

Previously, generating TLS certificate tas targeted fairly specifically
for use in kuma-cp deployments. Normalize the kumactl flags so that it
makes more sense to use kumactl generate self-signed TLS certificate
for any use case.

### Full changelog

* kumactl TLS certificate generation option `--cp-hostname` renamed to `--hostname`
* kumactl TLS certificate generator no longer hardcodes "kuma" as the certificate subject
* kumactl TLS certificate generator no longer hardcodes "localhost" into the certificate DNS names

### Issues resolved

Fix #3009 

### Documentation

https://github.com/kumahq/kuma-website/issues/574

### Testing

- [x] Unit tests
- [x] E2E tests
- [x] Manual testing on Universal
- [ ] Manual testing on Kubernetes 

### Backwards compatibility

- [ ] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.

### CODE REVIEW

File: app/kumactl/cmd/generate/generate_certificate.go [hunk 1]
```diff
@@ -21,59 +22,84 @@ type generateCertificateContext struct {
...
+			if err != nil {
 				return errors.Wrap(err, "could not write the cert file")
 			}
-			_, err = cmd.OutOrStdout().Write([]byte(fmt.Sprintf(`Certificates generated
-Key was saved in: %s
-Cert was saved in: %s
-`, ctx.args.key, ctx.args.cert)))
-			return err
+
+			if ctx.args.cert != "-" && ctx.args.key != "-" {
```
Comment (michaelbeaumont) [inline app/kumactl/cmd/generate/generate_certificate.go:79]: A user could output one to stdout and one to file

**Review by michaelbeaumont — APPROVED** [review]
LGTM

File: app/kumactl/cmd/generate/generate_certificate.go (hunk 1 above)
Comment (jpeach) [reply app/kumactl/cmd/generate/generate_certificate.go:79]: Yeh, in that case emitting a message to stdout would still cause problems for tooling. For example, simple stuff like this would not work:

```bash
$ kumactl generate tls-certificate --hostname echo.example.com --key-file - --type server 2>/dev/null | base64  -w 0
```

What we could do it always print the message to stderr, though IMHO that's a bit unexpected. WDYT?

**Review by bartsmykla — APPROVED** [review]
lgtm

File: app/kumactl/cmd/generate/generate_certificate.go (hunk 1 above)
Comment (michaelbeaumont) [reply app/kumactl/cmd/generate/generate_certificate.go:79]: No, you're right. It's good the way it is.
