### PR TITLE
fix(kuma-dp): pass sockets in metadata from dp to cp

### LINKED ISSUE #5228: access-log-streamer has different TMPDIR than Envoy
### What happened?

If `TMPDIR` env variable is different between `kuma-dp` and Envoy that will cause the listener configuration failure. This issue was reported via Kong slack.

Trimmed logs (ping me for full):

```
2022-10-21T10:57:22.767+0200	INFO	access-log-streamer	creating access log pipe	{"file": "/home/USER_X/tmp/kuma-al-a-b.sock"} # line 16
...
[2022-10-21 10:57:26.427][77617][warning][config] [source/common/config/grpc_subscription_impl.cc:126] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) outbound:127.0.0.1:50013: unable to open file '/home/USER_Y/tmp/kuma-al-a-b.sock': No such file or directory # line 134
```

This is because `AccessLogSocketName` is based on `os.TempDir` that is based on `TMPDIR`:

https://github.com/kumahq/kuma/blob/e00d8d886d87a476c350b51a695a2b84e2c2377b/pkg/xds/envoy/sockets.go#L12

Possible solutions:
- introduce an explicit working dir of Kuma DP and hold files there

### PR DESCRIPTION
**Pull request by lahabana**
Currently socket paths where generated from both the cp and dp. These relied on `os.TempDir()` which may return different results as they run on 2 different machines.

With this change we make the paths configurable from the kuma-dp process.
The information is then sent in the metadata and can be used during config generation.

From a backward compatibility POV there are 2 things to take care of:

- We may update the CP and have an old DP still running (the metadata won't have the entries for sockets).
- We may have an old DP bootstrap on a newer CP (this bootstrap request won't have the DP set).

Fix #5228

### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues --
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [x] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

File: pkg/core/xds/sockets.go [hunk 1]
```diff
@@ -0,0 +1,26 @@
+package xds
+
+import (
+	"fmt"
+	"path/filepath"
+)
+
+// TODO inline these in kuma-dp once backward compatibility is removed.
```
Comment (lahabana) [inline pkg/core/xds/sockets.go:8]:
```suggestion
// TODO inline these in kuma-dp once backward compatibility is removed. https://github.com/kumahq/kuma/issues/7220
```

File: pkg/core/xds/metadata.go [hunk 2]
```diff
@@ -133,55 +138,66 @@ func (m *DataplaneMetadata) GetVersion() *mesh_proto.Version {
...
+				metadata.Resource = r
+			default:
+				metadataLog.Error(err, "invalid dataplane resource type",
+					"resource", r.Descriptor().Name,
+					"field", FieldDataplaneDataplaneResource,
+					"value", value)
+			}
 		}
 	}
+	// TODO Backward compat for 2 versions after 2.4 prior to 2.4 these were not passed in the metadata
```
Comment (lahabana) [inline pkg/core/xds/metadata.go:173]:
```suggestion
	// TODO Backward compat for 2 versions after 2.4 prior to 2.4 these were not passed in the metadata https://github.com/kumahq/kuma/issues/7220 (remove the parameter tmpDir of the function too)
```

File: pkg/core/xds/metadata_test.go [hunk 3]
```diff
@@ -79,6 +97,38 @@ var _ = Describe("DataplaneMetadataFromXdsMetadata", func() {
 		}),
 	)
 
+	It("should fallback to service side generated paths", func() { // this has to be separate test because Equal does not work on proto
```
Comment (lahabana) [inline pkg/core/xds/metadata_test.go:100]:
```suggestion
	It("should fallback to service side generated paths", func() { // remove with https://github.com/kumahq/kuma/issues/7220
```

File: pkg/xds/bootstrap/generator.go [hunk 4]
```diff
@@ -80,32 +82,48 @@ func (b *bootstrapGenerator) Generate(ctx context.Context, request types.Bootstr
 	if err := b.validateRequest(request); err != nil {
 		return nil, kumaDpBootstrap, err
 	}
+	// TODO Backward compat for 2 versions after 2.4 prior to 2.4 these were not passed in the request
```
Comment (lahabana) [inline pkg/xds/bootstrap/generator.go:85]:
```suggestion
	// TODO Backward compat for 2 versions after 2.4 prior to 2.4 these were not passed in the request https://github.com/kumahq/kuma/issues/7220
```

File: pkg/xds/bootstrap/generator.go [hunk 5]
```diff
@@ -70,6 +71,7 @@ type bootstrapGenerator struct {
 	hostsAndIps             SANSet
 	hdsEnabled              bool
 	defaultAdminPort        uint32
+	TmpDir                  string
```
Comment (lobkovilya) [inline pkg/xds/bootstrap/generator.go:74]: Is it used?

**Review by lobkovilya — APPROVED** [review]

**Review by jakubdyszkiewicz — APPROVED** [review]
Looks good. I think long term we should introduce "dp data" directory to store sockets tokens etc. It's a bit meh to store sockets in tmp from the permission perspective.

**Comment by lahabana** [comment]
100% opened an issue to do this in the future
