### PR TITLE
fix(kuma-cp): prevent violating kubernetes label limit

### LINKED ISSUE #9168: ZoneIngress fails to sync to zone due to limitation on kubernetes label length
### What happened?

When syncing a ZoneIngress with a long name from the global control plane, the zone control plane complains that metadata.labels cannot be longer than 63 characters:

> 2024-02-07T17:43:00.180Z	INFO	kds-delta-zone	error during callback received, sending NACK	{"kds-version": "v2", "err": "failed to create k8s resource: ZoneIngress.kuma.io \"domain-discovery-onprem.domain-discovery-aws.kuma-ingress-5bc8f5f985-96hjz.kuma.default-2wwx5vw4c9fwc8zx\" is invalid: metadata.labels: Invalid value: \"domain-discovery-onprem.domain-discovery-aws.kuma-ingress-5bc8f5f985-96hjz.kuma.default-2wwx5vw4c9fwc8zx\": must be no more than 63 characters", "errVerbose": "ZoneIngress.kuma.io \"domain-discovery-onprem.domain-discovery-aws.kuma-ingress-5bc8f5f985-96hjz.kuma.default-2wwx5vw4c9fwc8zx\" is invalid: metadata.labels: Invalid value: \"domain-discovery-onprem.domain-discovery-aws.kuma-ingress-5bc8f5f985-96hjz.kuma.default-2wwx5vw4c9fwc8zx\": must be no more than 63 characters\nfailed to create k8s resource\ngithub.com/kumahq/kuma/pkg/plugins/resources/k8s.(*KubernetesStore).Create\n\tgithub.com/kumahq/kuma/pkg/plugins/resources/k8s/store.go:80\ngithub.com/kumahq/kuma/pkg/core/resources/store.(*paginationStore).Create\n\tgithub.com/kumahq/kuma/pkg/core/resources/store/pagination_store.go:30\ngithub.com/kumahq/kuma/pkg/metrics/store.(*MeteredStore).Create\n\tgithub.com/kumahq/kuma/pkg/metrics/store/store.go:44\ngithub.com/kumahq/kuma/pkg/core/resources/store.(*customizableResourceStore).Create\n\tgithub.com/kumahq/kuma/pkg/core/resources/store/customizable_store.go:44\ngithub.com/kumahq/kuma/pkg/kds/v2/store.(*syncResourceStore).Sync.func2\n\tgithub.com/kumahq/kuma/pkg/kds/v2/store/sync.go:230\ngithub.com/kumahq/kuma/pkg/core/resources/store.InTx\n\tgithub.com/kumahq/kuma/pkg/core/resources/store/transactions.go:46\ngithub.com/kumahq/kuma/pkg/kds/v2/store.(*syncResourceStore).Sync\n\tgithub.com/kumahq/kuma/pkg/kds/v2/store/sync.go:205\ngithub.com/kumahq/kuma/pkg/kds/zone.Setup.func2.ZoneSyncCallback.func3\n\tgithub.com/kumahq/kuma/pkg/kds/v2/store/sync.go:305\ngithub.com/kumahq/kuma/pkg/kds/v2/client.(*kdsSyncClient).Receive\n\tgithub.com/kumahq/kuma/pkg/kds/v2/client/kds_client.go:90\ngithub.com/kumahq/kuma/pkg/kds/zone.Setup.func2.1\n\tgithub.com/kumahq/kuma/pkg/kds/zone/components.go:134\nruntime.goexit\n\truntime/asm_amd64.s:1650"}

In this multi-zone setup there is a global control plane and two zones, `domain-discovery-aws` and `domain-discovery-onprem` 

## Info
Kuma version: 2.6.0 (dp, cp, zone ingress all have the same version)
kuberntes: 1.28.4
Kuma was previously running 2.4.3 and was upgraded to 2.6.0

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**
### Checklist prior to review

Fix #9168

Introduce limit for mesh name to 63. This is a limit of a label in Kubernetes. Since attach policy to a mesh via label, there is no way to attach a policy if a mesh name is longer than 63 chars. Store `display-name` as annotation on Kubernetes to escape the limit of 63 chars.
Other labels already have a validation of 63 chars.

- [ ] [Link to relevant issue][1] as well as docs and UI issues --
- [ ] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [ ] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [ ] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

File: pkg/core/managers/apis/mesh/mesh_validator.go [hunk 1]
```diff
@@ -31,6 +31,11 @@ func NewMeshValidator(caManagers core_ca.Managers, store core_store.ResourceStor
 }
 
 func (m *meshValidator) ValidateCreate(ctx context.Context, name string, resource *core_mesh.MeshResource) error {
+	if len(name) > 63 {
+		var verr validators.ValidationError
+		verr.AddViolation("name", "cannot be longer than 63 characters")
+		return verr.OrNil()
```
Comment (lahabana) [inline pkg/core/managers/apis/mesh/mesh_validator.go:37]: Why returning early? It's quite nice when validation shows all existing errors

File: test/e2e_env/multizone/sync/sync.go [hunk 2]
```diff
@@ -217,5 +217,24 @@ spec:
 				Expect(err).To(HaveOccurred())
 			})
 		})
+
+		It("should sync policy with a long name and store it as display name", func() {
```
Comment (lahabana) [inline test/e2e_env/multizone/sync/sync.go:221]: Doesn't it make sense to add one with a pod with the longest possible name to catch future bugs like this.

Comment (jakubdyszkiewicz) [reply test/e2e_env/multizone/sync/sync.go:221]: So adding Pod with 253 chars ends up with error on my mac
```
E0212 12:45:49.211145       7 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_sync(4397c70d-6737-4045-964b-ff9ef9f9d41a)\" with CreatePodSandboxError: \"Failed to create log directory for pod \\\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_sync(4397c70d-6737-4045-964b-ff9ef9f9d41a)\\\": mkdir /var/log/pods/sync_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_4397c70d-6737-4045-964b-ff9ef9f9d41a: file name too long\"" pod="sync/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" podUID=4397c70d-6737-4045-964b-ff9ef9f9d41a
```

Seems like hit limit of file name length HFS and extFS has a limit of 255. Not sure if this is K3D thing or Kubernetes overall (creating this filename). Do you still want me to add a test with ~200 chars?

Comment (lahabana) [reply test/e2e_env/multizone/sync/sync.go:221]: Lol :) I'm curious if this sort of test passes on Linux. It's likely ok to ignore this test for now to not block progress on this here.

File: pkg/plugins/resources/k8s/store.go [hunk 3]
```diff
@@ -231,6 +235,16 @@ func k8sNameNamespace(coreName string, scope k8s_model.Scope) (string, string, e
 	}
 }
 
+func splitLabelsAndAnnotations(coreLabels map[string]string) (map[string]string, map[string]string) {
```
Comment (lobkovilya) [inline pkg/plugins/resources/k8s/store.go:238]: please add a comment for this function, something like:
> Kuma resource labels are generally stored on Kubernetes as labels, except "kuma.io/display-name". We store it as an annotation because the resource name on k8s is limited by 253 and the label value is limited by 63.

**Review by lobkovilya — APPROVED** [review]
