### PR TITLE
fix(meshfaultinjection): deprecate spec.from field

### LINKED ISSUE #12380: MeshFaultInjection deprecate `spec.from`
### Description

Once https://github.com/kumahq/kuma/issues/12373 is implemented, there are no advantages in choosing `spec.from` over `spec.rules`. We should deprecate `spec.from`.

### PR DESCRIPTION
**Pull request by Automaat**
## Motivation

`spec.from` in MeshFaultInjection is superseded by `spec.rules` which provides equivalent functionality. Deprecating `spec.from` steers users toward the preferred API.

## Implementation information

Added `'from' field is deprecated, use 'rules' instead` deprecation warning when `spec.from` is non-empty, consistent with the pattern used in MeshTimeout, MeshRateLimit, and other policies. Existing MeshService-kind deprecation warning is preserved and nested inside the `from` check.

## Supporting documentation

Fix #12380

> Changelog: fix(meshfaultinjection): deprecate spec.from field

### CODE REVIEW

File: pkg/plugins/policies/meshfaultinjection/api/v1alpha1/deprecated.go [hunk 1]
```diff
@@ -7,11 +7,14 @@ import (
...
-	deprecations := validators.TopLevelTargetRefDeprecations(t.Spec.TargetRef)
-	for _, f := range pointer.Deref(t.Spec.From) {
-		if f.GetTargetRef().Kind == v1alpha1.MeshService {
-			deprecations = append(deprecations, "MeshService value for 'from[].targetRef.kind' is deprecated, use MeshSubset with 'kuma.io/service' instead")
+	var deprecations []string
+	if len(pointer.Deref(t.Spec.From)) > 0 {
+		deprecations = append(deprecations, "'from' field is deprecated, use 'rules' instead")
+		for _, f := range pointer.Deref(t.Spec.From) {
+			if f.GetTargetRef().Kind == v1alpha1.MeshService {
+				deprecations = append(deprecations, "MeshService value for 'from[].targetRef.kind' is deprecated, use MeshSubset with 'kuma.io/service' instead")
```
Comment (lahabana) [inline pkg/plugins/policies/meshfaultinjection/api/v1alpha1/deprecated.go]: Isn't MeshSubset deprecated as well?

File: pkg/plugins/policies/meshfaultinjection/api/v1alpha1/deprecated.go [hunk 2]
```diff
@@ -7,11 +7,14 @@ import (
 )
 
 func (t *MeshFaultInjectionResource) Deprecations() []string {
-	deprecations := validators.TopLevelTargetRefDeprecations(t.Spec.TargetRef)
-	for _, f := range pointer.Deref(t.Spec.From) {
-		if f.GetTargetRef().Kind == v1alpha1.MeshService {
-			deprecations = append(deprecations, "MeshService value for 'from[].targetRef.kind' is deprecated, use MeshSubset with 'kuma.io/service' instead")
+	var deprecations []string
+	if len(pointer.Deref(t.Spec.From)) > 0 {
+		deprecations = append(deprecations, "'from' field is deprecated, use 'rules' instead")
```
Comment (lahabana) [inline pkg/plugins/policies/meshfaultinjection/api/v1alpha1/deprecated.go]: To go with rules you need to use spiffe no?
