### PR TITLE
fix(install): bring back install metrics, tracing, logging

### LINKED ISSUE #4376: make "kumactl install metrics/logging/tracing" backward compatible
### What happened?

After consolidating "kumactl install metrics/logging/tracing" into one command "kumactl install observability" (PR: #4096) we dropped the support for "kumactl install metrics/logging/tracing". This means if someone runs "kumactl install metrics" they will get an error message "please use kumactl install observability" and the process will exit with exit code = 1. This will break people's automated scripts (e.g. to demo some feature).

Possible approaches:
1. Alias "kumactl install metrics" to "kumactl install observability --components prometheus,grafana" (and do similar mapping for other commands). Print a warning that the command is deprecated and will be removed in some version.
2. Alias "kumactl install metrics" to "kumactl install observability" without specifying components.

### PR DESCRIPTION
**Pull request by slonka**
Signed-off-by: slonka <slonka@users.noreply.github.com>

### Summary

This PR re-introduces `kumactl install metrics/tracing/logging` with a warning that says those commands are deprecated and a user should use `kumactl install observability`.

### Full changelog

* Fix: https://github.com/kumahq/kuma/issues/4376. 

### Issues resolved

Fix #4376

### Documentation

- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)

### Testing

- [x] Unit tests
- [x] E2E tests
- ~~[ ] Manual testing on Universal~~ (does not apply)
- [x] Manual testing on Kubernetes

### Backwards compatibility

- [x] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to take when upgrading.
- ~~[ ] Add `backport-to-stable` label if the code follows our [backporting policy](/CONTRIBUTING.md#backporting)~~

### CODE REVIEW

File: test/framework/deployments/tracing/kubernetes.go [hunk 1]
```diff
@@ -17,7 +17,7 @@ type k8SDeployment struct {
 var _ Deployment = &k8SDeployment{}
 
 func (t *k8SDeployment) ZipkinCollectorURL() string {
-	return fmt.Sprintf("http://jaeger-collector.%s:9411/api/v2/spans", framework.Config.DefaultObservabilityNamespace)
+	return fmt.Sprintf("http://jaeger-collector.%s:9411/api/v2/spans", framework.Config.DefaultTracingNamespace)
```
Comment (lahabana) [inline test/framework/deployments/tracing/kubernetes.go:20]: Won't this break as we're using the new tool and the tracing gets installed in the obs namespace?

File: mk/kind.mk [hunk 2]
```diff
@@ -129,6 +129,11 @@ kind/deploy/observability: build/kumactl
 	@KUBECONFIG=$(KIND_KUBECONFIG) ${BUILD_ARTIFACTS_DIR}/kumactl/kumactl install observability | KUBECONFIG=$(KIND_KUBECONFIG) kubectl apply -f -
 	@KUBECONFIG=$(KIND_KUBECONFIG) kubectl wait --timeout=60s --for=condition=Ready -n kuma-observability pods -l app=prometheus
 
+.PHONY: kind/deploy/metrics
+kind/deploy/metrics: build/kumactl
+	@KUBECONFIG=$(KIND_KUBECONFIG) ${BUILD_ARTIFACTS_DIR}/kumactl/kumactl install metrics | KUBECONFIG=$(KIND_KUBECONFIG) kubectl apply -f -
+	@KUBECONFIG=$(KIND_KUBECONFIG) kubectl wait --timeout=60s --for=condition=Ready -n kuma-metrics pods -l app=prometheus
```
Comment (lahabana) [inline mk/kind.mk:135]: I'm not sure this is useful to bring back

File: test/framework/config.go [hunk 3]
```diff
@@ -150,6 +151,7 @@ var defaultConf = E2eConfig{
 	KumaServiceName:               "kuma-control-plane",
 	KumaGlobalZoneSyncServiceName: "kuma-global-zone-sync",
 	DefaultObservabilityNamespace: "mesh-observability",
+	DefaultTracingNamespace:       "kuma-tracing",
```
Comment (lahabana) [inline test/framework/config.go:154]: Not sure we need to bring this back too

File: test/framework/kumactl.go [hunk 4]
```diff
@@ -151,6 +151,14 @@ func (k *KumactlOptions) KumactlInstallCP(mode string, args ...string) (string,
 		cmd...)
 }
 
+func (k *KumactlOptions) KumactlInstallMetrics() (string, error) {
+	return k.RunKumactlAndGetOutput("install", "metrics")
+}
+
+func (k *KumactlOptions) KumactlInstallTracing() (string, error) {
+	return k.RunKumactlAndGetOutput("install", "tracing")
+}
```
Comment (lahabana) [inline test/framework/kumactl.go:160]: Same I don't think it's needed

File: app/kumactl/cmd/install/install_logging.go [hunk 5]
```diff
@@ -1,18 +1,57 @@
...
+
+func newInstallLogging(pctx *kumactl_cmd.RootContext) *cobra.Command {
+	args := pctx.InstallLoggingContext.TemplateArgs
 	cmd := &cobra.Command{
 		Use:   "logging",
 		Short: "Install Logging backend in Kubernetes cluster (Loki)",
 		Long:  `Install Logging backend in Kubernetes cluster (Loki) in its own namespace.`,
 		RunE: func(cmd *cobra.Command, _ []string) error {
-			return errors.New("we're migrating to `observability`, please use `install observability`")
+			_, _ = cmd.ErrOrStderr().Write([]byte("we're migrating to `observability`, please use `install observability`"))
```
Comment (lahabana) [inline app/kumactl/cmd/install/install_logging.go:26]: There's `cobra.Command.Deprecated` maybe that would be a good way to do this and it might also add info to the docs we generate which would be cool

**Review by lahabana — COMMENTED** [review]
Thanks for doing this! Some comments but they are mostly nits

File: test/framework/deployments/tracing/kubernetes.go (hunk 1 above)
Comment (slonka) [reply test/framework/deployments/tracing/kubernetes.go:20]: forgot to revert that while copying stuff, good catch, thanks!

File: app/kumactl/data/fs.go [hunk 6]
```diff
@@ -16,6 +16,14 @@ func InstallLoggingFS() fs.FS {
 	return fsys
 }
 
+func InstallDeprecatedLoggingFS() fs.FS {
+	fsys, err := fs.Sub(InstallData, "install/k8s-deprecated/logging")
```
Comment (slonka) [inline app/kumactl/data/fs.go:20]: @lahabana - FYI, these are new

File: test/framework/deployments/tracing/kubernetes.go (hunk 1 above)
Comment (slonka) [reply test/framework/deployments/tracing/kubernetes.go]: Yes, that did break the tests, so they were not flaky but actually catching this regression! Fix on the way.

File: app/kumactl/cmd/install/install_logging.go (hunk 5 above)
Comment (slonka) [reply app/kumactl/cmd/install/install_logging.go]: done

File: test/framework/kumactl.go (hunk 4 above)
Comment (slonka) [reply test/framework/kumactl.go]: removed

File: test/framework/config.go (hunk 3 above)
Comment (slonka) [reply test/framework/config.go]: removed

File: mk/kind.mk (hunk 2 above)
Comment (slonka) [reply mk/kind.mk]: removed

**Review by jakubdyszkiewicz — APPROVED** [review]
LGTM. Please create issue to remove this after two minor versions.

**Review by lahabana — APPROVED** [review]

File: app/kumactl/cmd/install/install_metrics.go [hunk 7]
```diff
@@ -1,18 +1,125 @@
...
+func newInstallMetrics(pctx *kumactl_cmd.RootContext) *cobra.Command {
+	args := pctx.InstallMetricsContext.TemplateArgs
+
 	cmd := &cobra.Command{
 		Use:   "metrics",
 		Short: "Install Metrics backend in Kubernetes cluster (Prometheus + Grafana)",
 		Long:  `Install Metrics backend in Kubernetes cluster (Prometheus + Grafana) in its own namespace.`,
 		RunE: func(cmd *cobra.Command, _ []string) error {
-			return errors.New("we're migrating to `observability`, please use `install observability`")
+			cmd.Deprecated = "we're migrating to `observability`, please use `install observability`"
```
[the remark this answers is not in the document]
Comment (slonka) [reply app/kumactl/cmd/install/install_metrics.go:26]: Wanted to edit the same line so the comment would get `outdated` but you're probably right - it will look more consistent as a field. Will fix it.

[the remark this answers is not in the document]
Comment (slonka) [reply app/kumactl/cmd/install/install_metrics.go]: fixed

File: app/kumactl/cmd/install/install_logging.go [hunk 8]
```diff
@@ -23,7 +23,7 @@ func newInstallLogging(pctx *kumactl_cmd.RootContext) *cobra.Command {
 		Short: "Install Logging backend in Kubernetes cluster (Loki)",
 		Long:  `Install Logging backend in Kubernetes cluster (Loki) in its own namespace.`,
 		RunE: func(cmd *cobra.Command, _ []string) error {
-			_, _ = cmd.ErrOrStderr().Write([]byte("we're migrating to `observability`, please use `install observability`"))
+			cmd.Deprecated = "we're migrating to `observability`, please use `install observability`"
```
[the remark this answers is not in the document]
Comment (slonka) [reply app/kumactl/cmd/install/install_logging.go]: Will fix that.
