### PR TITLE
fix(kuma-cp): improve ZoneInsight subscription management

### LINKED ISSUE #7535: ZoneInsights subscription are invalid
### What happened?

Multiple weird things here:
- not ordered by connectTime (the newest connection should always be last)
- a lot of non disconnected subscriptions seems to exist.

I've checked other insights and they don't seem to have this problem.

trimmed version using `pbpaste | jq '.zoneInsight.subscriptions | del(.[] | .status.stat) | del(.[] | .config) | del(.[] | .version)'`

```json
[
  {
    "id": "ef2f9da4-9b50-4b7f-9530-3efb897d9ebb",
    "globalInstanceId": "mink-control-plane-57cdd67669-bz6n9-9bd1",
    "connectTime": "2023-08-16T15:46:54.968654235Z",
    "status": {
      "lastUpdateTime": "2023-08-16T15:46:56.242911919Z",
      "total": {
        "responsesSent": "37",
        "responsesAcknowledged": "37"
      }
    },
    "generation": 383
  },
  {
    "id": "31f30740-bc80-4811-a262-4fcf467237b3",
    "globalInstanceId": "mink-control-plane-57cdd67669-bz6n9-9bd1",
    "connectTime": "2023-08-17T02:09:47.353040574Z",
    "status": {
      "lastUpdateTime": "2023-08-17T02:09:47.853503539Z",
      "total": {
        "responsesSent": "37",
        "responsesAcknowledged": "37"
      }
    },
    "generation": 133
  },
  {
    "id": "c0cd81d9-00fa-4c36-9b98-9c1d43fc6a57",
    "globalInstanceId": "mink-control-plane-57cdd67669-bz6n9-9bd1",
    "connectTime": "2023-08-16T17:09:12.650835657Z",
    "status": {
      "lastUpdateTime": "2023-08-16T17:09:13.281269475Z",
      "total": {
        "responsesSent": "37",
        "responsesAcknowledged": "37"
      }
    },
    "generation": 350
  },
  {
    "id": "6a67e101-b92c-4256-8ab9-1372534c6055",
    "globalInstanceId": "mink-control-plane-57cdd67669-bz6n9-9bd1",
    "connectTime": "2023-08-16T17:57:08.027177564Z",
    "status": {
      "lastUpdateTime": "2023-08-16T17:57:08.576920005Z",
      "total": {
        "responsesSent": "37",
        "responsesAcknowledged": "37"
      }
    },
    "generation": 330
  },
  {
    "id": "88aa4963-5a7d-4bcf-9b7e-3612d5d8919c",
    "globalInstanceId": "mink-control-plane-57cdd67669-bz6n9-9bd1",
    "connectTime": "2023-08-17T03:58:56.543362277Z",
    "status": {
      "lastUpdateTime": "2023-08-17T03:58:57.020392357Z",
      "total": {
        "responsesSent": "37",
        "responsesAcknowledged": "37"
      }
    },
    "generation": 90
  },
  {
    "id": "a2ce13f7-d28f-4cab-adab-59a1fa46022f",
    "globalInstanceId": "mink-control-plane-57cdd67669-bz6n9-9bd1",
    "connectTime": "2023-08-17T05:04:30.305811060Z",
    "disconnectTime": "2023-08-17T05:21:11.798920035Z",
    "status": {
      "lastUpdateTime": "2023-08-17T05:10:16.240163448Z",
      "total": {
        "responsesSent": "9"
      }
    },
    "generation": 4
  },
  {
    "id": "5891e6db-cd9e-46f2-b4fe-2f3b805d76b6",
    "globalInstanceId": "mink-control-plane-57cdd67669-bcknf-0676",
    "connectTime": "2023-08-17T06:19:04.295324637Z",
    "status": {
      "lastUpdateTime": "2023-08-17T06:19:05.577959060Z",
      "total": {
        "responsesSent": "37",
        "responsesAcknowledged": "37"
      }
    },
    "generation": 34
  },
  {
    "id": "4f4c66d6-c236-49f1-8181-f32adc887a17",
    "globalInstanceId": "mink-control-plane-57cdd67669-bz6n9-9bd1",
    "connectTime": "2023-08-16T20:47:24.425755529Z",
    "status": {
      "lastUpdateTime": "2023-08-16T20:47:25.021264998Z",
      "total": {
        "responsesSent": "37",
        "responsesAcknowledged": "37"
      }
    },
    "generation": 262
  },
  {
    "id": "2b9e341c-264b-4af4-bd64-0b00873985be",
    "globalInstanceId": "mink-control-plane-57cdd67669-bz6n9-9bd1",
    "connectTime": "2023-08-17T07:15:51.868865656Z",
    "status": {
      "lastUpdateTime": "2023-08-17T07:15:52.568221582Z",
      "total": {
        "responsesSent": "37",
        "responsesAcknowledged": "37"
      }
    },
    "generation": 11
  },
  {
    "id": "f491c00d-dd66-488c-87dd-d456d87ed15e",
    "globalInstanceId": "mink-control-plane-57cdd67669-bz6n9-9bd1",
    "connectTime": "2023-08-17T00:06:58.387319166Z",
    "status": {
      "lastUpdateTime": "2023-08-17T00:06:58.934255144Z",
      "total": {
        "responsesSent": "37",
        "responsesAcknowledged": "37"
      }
    },
    "generation": 183
  }
]
```

full version:
[insights.txt](https://github.com/kumahq/kuma/files/12366920/insights.txt)

### PR DESCRIPTION
**Pull request by michaelbeaumont**
See #7535 

### Checklist prior to review

- [x] [Link to relevant issue][1] as well as docs and UI issues --
- [x] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Tests (Unit test, E2E tests, manual test on universal and k8s) --
  - Don't forget `ci/` labels to run additional/fewer tests
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? ([this](https://github.com/kumahq/kuma/actions/workflows/auto-backport.yaml) GH action will add "backport" label based on these [file globs](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L6), if you want to prevent it from adding the "backport" label use [no-backport-autolabel](https://github.com/kumahq/kuma/blob/master/.github/workflows/auto-backport.yaml#L8) label) --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

File: api/generic/insights.go [hunk 1]
```diff
@@ -9,7 +9,10 @@ import (
 type Insight interface {
 	proto.Message
 	IsOnline() bool
+	// TODO Deprecated: bad
```
Comment (lahabana) [inline api/generic/insights.go:12]:
```suggestion
	// Deprecated: bad
```

That way in IDEs there usages are strikethrough

File: api/mesh/v1alpha1/dataplane_insight_helpers.go [hunk 2]
```diff
@@ -56,13 +56,23 @@ func (x *DataplaneInsight) IsOnline() bool {
 	return false
 }
 
-func (x *DataplaneInsight) GetSubscription(id string) (int, *DiscoverySubscription) {
-	for i, s := range x.GetSubscriptions() {
+func (x *DataplaneInsight) GetOnlineSubscriptions() []generic.Subscription {
```
Comment (lahabana) [inline api/mesh/v1alpha1/dataplane_insight_helpers.go:59]: Rather than the dupe code should we have a type and methods around `[]generaic.Subcription` ? Feels like this repetition is easily avoidable no?

File: api/generic/insights.go (hunk 1 above)
Comment (michaelbeaumont) [reply api/generic/insights.go:12]: I want to remove it in this PR

File: api/mesh/v1alpha1/dataplane_insight_helpers.go (hunk 2 above)
Comment (michaelbeaumont) [reply api/mesh/v1alpha1/dataplane_insight_helpers.go:59]: The problem is that each insight has a different slice of concrete type. My go generics knowledge is not the best but I don't think you can write this in a generic way. You end up always having to create a list of `generic.Subscription` and then add each non-generic element in a `for` loop, AFAICT.

File: pkg/xds/server/callbacks/dataplane_lifecycle.go [hunk 3]
```diff
@@ -251,8 +251,12 @@ func (d *DataplaneLifecycle) proxyConnectedToAnotherCP(
...
 	}
 
-	sub := insight.GetSpec().(generic.Insight).GetLastSubscription().(*mesh_proto.DiscoverySubscription)
-	if sub != nil && sub.ControlPlaneInstanceId != d.cpInstanceID {
+	subs := insight.GetSpec().(generic.Insight).AllSubscriptions()
+	if len(subs) == 0 {
+		return false, nil
+	}
+
+	if sub := subs[len(subs)-1].(*mesh_proto.DiscoverySubscription); sub.ControlPlaneInstanceId != d.cpInstanceID {
```
Comment (michaelbeaumont) [inline pkg/xds/server/callbacks/dataplane_lifecycle.go:259]: @jakubdyszkiewicz it's not clear to me whether we want to change this logic. It's not quite the same mistake as in the finalizer. Checking the last subscription here seems to just be a way to assign responsibility for deleting the `Dataplane` resource.

This idea seems unrelated to the online/offline management

File: api/mesh/v1alpha1/dataplane_insight_helpers.go (hunk 2 above)
Comment (lobkovilya) [reply api/mesh/v1alpha1/dataplane_insight_helpers.go]: As an option, you can create a separate generic method like:
```go
func AllSubscriptions[S Subscription, T interface{ GetSubscriptions() []S }](t T) []Subscription {
	var subs []Subscription
	for _, s := range t.GetSubscriptions() {
		subs = append(subs, s)
	}
	return subs
}
```
and call it from `AllSubscription` methods for all insights:
```go
func (x *DataplaneInsight) AllSubscriptions() []generic.Subscription {
	return generic.AllSubscriptions[*DiscoverySubscription](x)
}
```

The same could be done for UpdateSubscription, but you must add `SetSubscriptions()` methods to all insights.

File: pkg/xds/server/callbacks/dataplane_lifecycle.go (hunk 3 above)
Comment (jakubdyszkiewicz) [reply pkg/xds/server/callbacks/dataplane_lifecycle.go:259]: I'm not sure. Technically it shouldn't matter. I think it's fine either way but we can keep it as is to minimize changes

Comment (michaelbeaumont) [reply pkg/xds/server/callbacks/dataplane_lifecycle.go:259]: I'm going to leave it. It's not clear to me how or why it should even work differently. What should the check even be? The fact that there may be another online subscription seems irrelevant here. The subscription has already been disconnected by this point by the dataplane status tracker.

File: api/system/v1alpha1/zone_insight_helpers.go [hunk 4]
```diff
@@ -64,13 +72,14 @@ func (x *ZoneInsight) UpdateSubscription(s generic.Subscription) error {
...
-	} else {
-		x.finalizeSubscriptions()
-		x.Subscriptions = append(x.Subscriptions, kdsSubscription)
+	for i, sub := range x.GetSubscriptions() {
+		if sub.GetId() == kdsSubscription.Id {
+			x.Subscriptions[i] = kdsSubscription
+			return nil
+		}
 	}
+	x.finalizeSubscriptions()
```
Comment (jakubdyszkiewicz) [inline api/system/v1alpha1/zone_insight_helpers.go:81]: I thought that we discussed that we want to drop this call

Comment (michaelbeaumont) [reply api/system/v1alpha1/zone_insight_helpers.go:81]: Yeah. Wasn't sure whether to put it in this PR since it causes somewhat different problems but I've added it

Comment (michaelbeaumont) [reply api/system/v1alpha1/zone_insight_helpers.go]: @lobkovilya

File: pkg/gc/finalizer.go [hunk 5]
```diff
@@ -149,29 +146,41 @@ func (f *subscriptionFinalizer) checkGeneration(ctx context.Context, typ core_mo
...
+				log.V(1).Info("mark subscription as disconnected", "id", id)
+				sub := insight.GetSubscription(id)
+				sub.SetDisconnectTime(now)
+				if err := insight.UpdateSubscription(sub); err != nil {
+					return errors.Wrapf(err, "unable to update subscription %s", id)
+				}
+			}
+			return nil
+		}); err != nil {
+			log.Error(err, "unable to upsert insight")
```
Comment (jakubdyszkiewicz) [inline pkg/gc/finalizer.go:179]: I know this was already like this but

This should be wrap not log + err. Also the log has no tenant context.

**Review by jakubdyszkiewicz — APPROVED** [review]

File: api/mesh/v1alpha1/dataplane_insight_helpers.go [hunk 6]
```diff
@@ -56,13 +56,17 @@ func (x *DataplaneInsight) IsOnline() bool {
...
 }
 
-func (x *DataplaneInsight) GetSubscription(id string) (int, *DiscoverySubscription) {
-	for i, s := range x.GetSubscriptions() {
+func (x *DataplaneInsight) AllSubscriptions() []generic.Subscription {
+	return generic.AllSubscriptions[*DiscoverySubscription](x)
+}
+
+func (x *DataplaneInsight) GetSubscription(id string) generic.Subscription {
+	for _, s := range x.GetSubscriptions() {
```
Comment (lobkovilya) [inline api/mesh/v1alpha1/dataplane_insight_helpers.go:64]: Unlike `UpdateSubscription` this one also should be pretty straightforward to convert into generic method like `AllSubscriptions`

File: pkg/gc/finalizer.go [hunk 7]
```diff
@@ -149,29 +146,41 @@ func (f *subscriptionFinalizer) checkGeneration(ctx context.Context, typ core_mo
...
 			return err
 		}
-		delete(f.insights[tenantID(tenantId)][typ], key)
+
+		f.insights[tenantID(tenantId)][typ][key] = newWatchedSubs
```
Comment (lobkovilya) [inline pkg/gc/finalizer.go:183]: If `newWatchedSubs` is empty then you can delete `key` from `f.insights`

File: pkg/gc/finalizer.go [hunk 8]
```diff
@@ -149,29 +146,41 @@ func (f *subscriptionFinalizer) checkGeneration(ctx context.Context, typ core_mo
...
 		}
 
-		old, ok := f.insights[tenantID(tenantId)][typ][key]
-		if !ok || old.id != insight.GetLastSubscription().GetId() || old.generation != insight.GetLastSubscription().GetGeneration() {
-			// something changed since the last check, either subscriptionId or generation were updated
-			// don't finalize the subscription, update map with fresh data
-			f.insights[tenantID(tenantId)][typ][key] = &descriptor{
-				id:         insight.GetLastSubscription().GetId(),
-				generation: insight.GetLastSubscription().GetGeneration(),
+		lastGens := f.insights[tenantID(tenantId)][typ][key]
```
Comment (lobkovilya) [inline pkg/gc/finalizer.go:149]: Should we rename `f.insights` to `f.onlineInsights`, so it's more obvious we're monitoring only insights that are still online

**Review by lobkovilya — APPROVED** [review]

File: api/system/v1alpha1/zone_insight_helpers.go (hunk 4 above)
Comment (lobkovilya) [reply api/system/v1alpha1/zone_insight_helpers.go]: But `finalizeSubscription` will close old subscriptions quicker than finalizer, right? So if 1 CP instance stopped ungracefully and DPP reconnects to another CP, then you'll immediately get old subscription closed

File: api/mesh/v1alpha1/dataplane_insight_helpers.go (hunk 6 above)
Comment (michaelbeaumont) [reply api/mesh/v1alpha1/dataplane_insight_helpers.go:64]: like the commit I added?

File: pkg/gc/finalizer.go (hunk 5 above)
Comment (michaelbeaumont) [reply pkg/gc/finalizer.go]: you meant return the wrapped error and don't log right? fixed

File: api/mesh/v1alpha1/dataplane_insight_helpers.go (hunk 6 above)
Comment (lobkovilya) [reply api/mesh/v1alpha1/dataplane_insight_helpers.go]: yes 👍

File: api/system/v1alpha1/zone_insight_helpers.go (hunk 4 above)
Comment (michaelbeaumont) [reply api/system/v1alpha1/zone_insight_helpers.go]: But I don't think they necessarily stay disconnected. In [my original PR](https://github.com/kumahq/kuma/pull/8144) I describe how I believe in the ungraceful case, `ZoneInsightSink` can in fact _unset_ the disconnected time because it doesn't check the current state.

Comment (lobkovilya) [reply api/system/v1alpha1/zone_insight_helpers.go]: Right, why did we drop this idea? We should probably check `DisconnectTime` before updating the subscription to avoid the unset.

Comment (michaelbeaumont) [reply api/system/v1alpha1/zone_insight_helpers.go]: I'm not sure, I've come around to "let finalizer handle all disconnects". It's somehow odd to have two different sources of truth for disconnection state, one in UpdateSubscription and one in finalizer. @jakubdyszkiewicz

File: pkg/gc/finalizer.go [hunk 9]
```diff
@@ -140,38 +141,55 @@ func (f *subscriptionFinalizer) checkGeneration(ctx context.Context, typ core_mo
 	f.removeDeletedInsights(insights, tenantId)
 
 	for _, item := range insights.GetItems() {
-		log := finalizerLog.WithValues("type", typ, "name", item.GetMeta().GetName(), "mesh", item.GetMeta().GetMesh())
+		logger := finalizerLog.WithValues("type", typ, "name", item.GetMeta().GetName(), "mesh", item.GetMeta().GetMesh())
+		logger = log.AddFieldsFromCtx(logger, ctx, f.extensions)
```
Comment (lahabana) [inline pkg/gc/finalizer.go:145]: Why do we need these extensions everywhere in the logger? I've used them as well and it's super annoying and confusing to folks...

Feels like this may be one of the rare places where a global might be easier to use...

Comment (lahabana) [reply pkg/gc/finalizer.go:145]: Hoo https://github.com/kumahq/kuma/pull/8184 support of slog in Logger. Wondering if InfoWithContext/ErrorWithContext can make all this a lot easier

Comment (michaelbeaumont) [reply pkg/gc/finalizer.go:145]: @lahabana should we reexamine AddFieldsFromCtx in a differnet issue?

Comment (lahabana) [reply pkg/gc/finalizer.go:145]: Ho yes of course!

Comment (lahabana) [reply pkg/gc/finalizer.go:145]: https://github.com/kumahq/kuma/issues/8216
