### PR TITLE
fix(kuma-cp): reissue admin tls cert on dp address change

### LINKED ISSUE #5221: Envoy Admin mTLS certs should be regenerated on DP address change
### What happened?

Envoy Admin mTLS certs are not regenerated when DP address is changed (Kubernetes)

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**
Admin TLS certs were issued once. We need to reissue it when DP address changes.

Fix #5221

### Checklist prior to review

- [X] Link to docs PR or issue --
- [X] Link to UI issue or PR --
- [X] Is the [issue worked on linked][1]? -- https://github.com/kumahq/kuma/issues/5221
- [X] The PR does not hardcode values that might break projects that depend on kuma (e.g. "kumahq" as a image registry) --
- [X] The PR will work for both Linux and Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [X] Unit Tests --
- [X] E2E Tests -- no, hard to execute
- [X] Manual Universal Tests -- no, hard to execute
- [X] Manual Kubernetes Tests -- no, hard to execute
- [X] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [X] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? -- although this is a bug, I don't think it qualifies for backporting.
- [X] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Review by bartsmykla — APPROVED** [review]

File: pkg/xds/sync/dataplane_watchdog.go [hunk 1]
```diff
@@ -195,6 +196,7 @@ func (d *DataplaneWatchdog) getEnvoyAdminMTLS(ctx context.Context, address strin
 		// 2) have a stable certs = stable Envoy config
 		// This means that if we want to change Envoy Admin CA, we need to restart all CP instances.
```
Comment (lahabana) [inline pkg/xds/sync/dataplane_watchdog.go:197]: Maybe worth mentionning the dpAddress change here in the comments?
