### PR TITLE
fix(kds): Avoid calling `Send()` from different goroutines

### LINKED ISSUE #2492: Multi region kds sync stops with a lot of dataplanes
### Summary

The kds stream seams to stop sending/receiving updates to some clients when there is a lot of dataplanes (> 200).

### Steps To Reproduce

I have only been able to reproduce using real sidecars in staging environment (I think it might be related to the frequency of the dataplane insight update).

1. Create 2 dps, 1 global, 1 zone.
2. Create 200 meshes.
3. Create 200 dataplanes and launch the sidecars / kuma-dp process.
4. Create a new mesh, the mesh is not propagated to the zone.

### Additional Details & Logs

There is no error logs, the global seems to try to send the update to the zone, but the zone never receive the updates.
The counters of the zone insight stays to 1 sent, and is never acknowledged.

- Version 1.2.3
- No errors in the log, just hanging
- Linux
- Manual install
- I tried to bump the max grpc payload, but it was not working. (I dont have the error).

### PR DESCRIPTION
**Pull request by lahabana**
Rewrote most of KDS mux as it wasn't working as intended.
KDS mux now ensures:

- Recv() on underlying streams are always called in the same goroutine
- Send() on underlying streams are always called in the same goroutine
- Close() actually waits for some goroutine to terminate

Also added extra tests to ensure these invariants

Fixes #2492

### CODE REVIEW

**Comment by bchatelard** [comment]
Thanks! I just tested this fix (cherry-pick in 1.2.3) and it looks like it is solving my issue #2492

**Comment by lahabana** [comment]
@jakubdyszkiewicz noticed an issue with restarts of global which would not have remote reconnect. I need to look into this.

File: pkg/kds/mux/client.go [hunk 1]
```diff
@@ -14,10 +14,15 @@ import (
 
 	mesh_proto "github.com/kumahq/kuma/api/mesh/v1alpha1"
 	"github.com/kumahq/kuma/pkg/config/multizone"
+	"github.com/kumahq/kuma/pkg/core"
 	"github.com/kumahq/kuma/pkg/core/runtime/component"
 	"github.com/kumahq/kuma/pkg/metrics"
 )
 
+var (
+	muxClientLog = core.Log.WithName("kds-mux-client")
```
Comment (jpeach) [inline pkg/kds/mux/client.go:23]: The server log name is `mux-server`. We should be consistent, one way or the other.

File: pkg/kds/mux/session.go [hunk 2]
```diff
@@ -14,65 +17,115 @@ type Session interface {
...
+		cancel:  cancel,
 	}
 	go func() {
-		defer s.close()
-		if err := s.handle(stream, stop); err != nil {
-			s.err <- err
-		}
+		s.handleRecv(stream)
+	}()
+	s.wg.Add(1)
```
[the remark this answers is not in the document]
Comment (jpeach) [reply pkg/kds/mux/session.go:59]: Probably because this depends on the receive side getting closed by the GRPC runtime. But I think it would be a lot clearer if the wait was symmetric.

File: pkg/kds/mux/session.go [hunk 3]
```diff
@@ -14,65 +17,115 @@ type Session interface {
...
 		select {
-		case <-stop:
-			return nil
-		default:
-			if atomic.LoadInt32(&s.closed) == 1 {
-				return nil
+		case r := <-s.serverStream.bufferStream.sendBuffer:
+			if kdsVersion == KDSVersionV2 {
+				r = &mesh_proto.Message{Value: &mesh_proto.Message_LegacyResponse{LegacyResponse: DiscoveryResponseV2(r.GetResponse())}}
+			}
```
[the remark this answers is not in the document]
Comment (lahabana) [reply pkg/kds/mux/session.go:74]: Previous versions of Kuma.

File: pkg/kds/mux/session.go [hunk 4]
```diff
@@ -14,65 +17,115 @@ type Session interface {
...
+			s.serverStream.bufferStream.sendResult <- err
+		case r := <-s.clientStream.bufferStream.sendBuffer:
+			if kdsVersion == KDSVersionV2 {
+				r = &mesh_proto.Message{Value: &mesh_proto.Message_LegacyRequest{LegacyRequest: DiscoveryRequestV2(r.GetRequest())}}
 			}
+			err := stream.Send(r)
+			s.clientStream.bufferStream.sendResult <- err
+		case <-s.closing:
+			select {
+			case <-s.serverStream.bufferStream.sendBuffer:
```
[the remark this answers is not in the document]
Comment (lahabana) [reply pkg/kds/mux/session.go:85]: Thx it makes sense indeed. I was trying to stay away for Mutexes and trying to find the right way to write this.
I think this code achieves what I was trying to

[the remark this answers is not in the document]
Comment (jpeach) [reply pkg/kds/mux/session.go:85]: With a mutex approach, there's a risk of deadlocking if you need the goroutine and the caller to both hold mutexes. The trick I've used here is that the mutex only guards the write side of the stream object, protecting against closed channels.

File: pkg/kds/mux/client.go (hunk 1 above)
Comment (lahabana) [reply pkg/kds/mux/client.go:23]: I believe I've updated the mux-server to be kds-mux-server too.

**Comment by lahabana** [comment]
@jpeach @bchatelard @jakubdyszkiewicz  I've finally got around to updating this. I still want to check a couple of things but I think the code is ready to be reviewed.

File: pkg/kds/zone/components_test.go [hunk 5]
```diff
@@ -94,7 +88,9 @@ var _ = Describe("Zone Sync", func() {
 		zoneStore = memory.NewStore()
 		zoneSyncer = sync_store.NewResourceSyncer(core.Log.WithName("kds-syncer"), zoneStore)
 
-		start(newPolicySink(zoneName, zoneSyncer, clientStream, &testRuntimeContext{kds: kdsCtx}), stop)
+		go func() {
+			_ = newPolicySink(zoneName, zoneSyncer, clientStream, &testRuntimeContext{kds: kdsCtx}).Start()
+		}()
```
Comment (jpeach) [inline pkg/kds/zone/components_test.go:93]: I get a data race detected here:
```
WARNING: DATA RACE
Write at 0x00c00098ef70 by goroutine 62:
  github.com/kumahq/kuma/pkg/kds/zone_test.glob..func1.3()
      /home/jpeach/upstream/konghq/kuma/pkg/kds/zone/components_test.go:89 +0x679
...

Previous read at 0x00c00098ef70 by goroutine 140:
  github.com/kumahq/kuma/pkg/kds/zone_test.glob..func1.3.1()
      /home/jpeach/upstream/konghq/kuma/pkg/kds/zone/components_test.go:92 +0xbb

```

File: pkg/kds/zone/components_test.go [hunk 6]
```diff
@@ -94,7 +88,9 @@ var _ = Describe("Zone Sync", func() {
 		zoneStore = memory.NewStore()
 		zoneSyncer = sync_store.NewResourceSyncer(core.Log.WithName("kds-syncer"), zoneStore)
 
-		start(newPolicySink(zoneName, zoneSyncer, clientStream, &testRuntimeContext{kds: kdsCtx}), stop)
+		go func() {
```
Comment (jpeach) [inline pkg/kds/zone/components_test.go:91]: Should someone be waiting for the wait group above?

File: pkg/kds/mux/session.go [hunk 7]
```diff
@@ -89,21 +115,68 @@ func (s *session) PeerID() string {
...
 	}
 }
 
-func (s *session) close() {
-	close(s.done)
-	close(s.serverStream.requests)
-	close(s.clientStream.responses)
+func (k *bufferStream) put(message *mesh_proto.Message) {
+	k.recvBuffer <- message
+}
```
Comment (jpeach) [inline pkg/kds/mux/session.go:144]: Because this method is only called from `handleRecv` and that is the only place that calls `close()`, writing to the streamn without holding the lock is OK.

I experimented with locking this, but it makes tests timeout since it serialized WRT `Send()`. Probably a rwlock is the right choice (hold the write when setting the closed flag).

File: pkg/kds/mux/session.go [hunk 8]
```diff
@@ -12,67 +12,93 @@ type Session interface {
...
+				r = &mesh_proto.Message{Value: &mesh_proto.Message_LegacyResponse{LegacyResponse: DiscoveryResponseV2(r.GetResponse())}}
+			}
+			err := stream.Send(r)
+			itm.errChan <- err
+		case itm, more := <-s.clientStream.bufferStream.sendBuffer:
+			if !more {
+				return
+			}
+			r := itm.msg
+			if kdsVersion == KDSVersionV2 && r != nil {
```
Comment (jpeach) [inline pkg/kds/mux/session.go:97]: If `r` can actually be nil, then it still gets passed to `stream.Send`, which doesn't seem right?

File: pkg/kds/mux/session.go [hunk 9]
```diff
@@ -89,21 +115,68 @@ func (s *session) PeerID() string {
...
+	if k.closed {
+		k.lock.Unlock()
+		return io.EOF
+	}
+	errChan := make(chan error)
+	k.sendBuffer <- sendItem{msg: message, errChan: errChan}
+
+	k.lock.Unlock()
+	r := <-errChan
+	return r
```
Comment (jpeach) [inline pkg/kds/mux/session.go:157]:
```suggestion
return <-errChan
```

**Review by jpeach — APPROVED** [review]
Just a few nits and small issues. I also think it's worth adding explanatory comments while this is all fresh in your mind :)

File: pkg/kds/client/sink.go [hunk 10]
```diff
@@ -30,7 +33,7 @@ func NewKDSSink(log logr.Logger, rt []model.ResourceType, kdsStream KDSStream, c
 	}
 }
 
-func (s *kdsSink) Start(stop <-chan struct{}) (errs error) {
+func (s *kdsSink) Start() error {
```
[the remark this answers is not in the document]
Comment (lahabana) [reply pkg/kds/client/sink.go:36]: Great idea!

File: pkg/kds/mux/session.go [hunk 11]
```diff
@@ -12,67 +12,93 @@ type Session interface {
...
+			s.clientStream.bufferStream.put(msg)
+		}
+	}
+}
+
+func (s *session) handleSend(stream MultiplexStream) {
+	kdsVersion := KDSVersion(stream.Context())
+	for {
+		select {
+		case itm, more := <-s.serverStream.bufferStream.sendBuffer:
```
[the remark this answers is not in the document]
Comment (lahabana) [reply pkg/kds/mux/session.go:82]: But I wanted to save one keystroke :)

File: pkg/kds/zone/components_test.go (hunk 5 above)
Comment (lahabana) [reply pkg/kds/zone/components_test.go:93]: Yes that's part of the things I still need to check but I think it's a test only issue.

File: pkg/kds/mux/session.go (hunk 8 above)
Comment (lahabana) [reply pkg/kds/mux/session.go:97]: Actually forgot to remove the `r!=nil` which is not possible anymore
