### PR TITLE
fix(kuma-dp): resilient TCP access log streamer

### LINKED ISSUE #4859: TCP logging cannot recover after failed connection
### What happened?

After a TCP loggin rewrite, it cannot recover if destination is broken.

```
2022-08-18T16:27:56.832+0200	INFO	accesslogs-server	connected to TCP logging backend	{"streamID": 1, "address": "127.0.0.1:5050"}
2022-08-18T16:28:37.124+0200	INFO	accesslogs-server	Access Logs stream is terminated	{"streamID": 1, "totalRequests": 14}
2022-08-18T16:28:37.125+0200	ERROR	accesslogs-server	Access Logs stream terminated with an error	{"streamID": 1, "error": "failed to send a log entry to a TCP logging backend: 127.0.0.1:5050: write tcp 127.0.0.1:63712->127.0.0.1:5050: write: broken pipe", "errorVerbose": "write tcp 127.0.0.1:63712->127.0.0.1:5050: write: broken pipe\nfailed to send a log entry to a TCP logging backend: 127.0.0.1:5050\ngithub.com/kumahq/kuma/app/kuma-dp/pkg/dataplane/accesslogs/v3.(*sender).Send\n\t/Users/jakub/kong/kuma/app/kuma-dp/pkg/dataplane/accesslogs/v3/sender.go:33\ngithub.com/kumahq/kuma/app/kuma-dp/pkg/dataplane/accesslogs/v3.(*accessLogStreamer).StreamAccessLogs\n\t/Users/jakub/kong/kuma/app/kuma-dp/pkg/dataplane/accesslogs/v3/server.go:71\ngithub.com/kumahq/kuma/app/kuma-dp/pkg/dataplane/accesslogs.(*accessLogServer).Start.func2\n\t/Users/jakub/kong/kuma/app/kuma-dp/pkg/dataplane/accesslogs/server.go:62\nruntime.goexit\n\t/opt/homebrew/Cellar/go/1.18.2/libexec/src/runtime/asm_arm64.s:1263"}
```

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**
After recent changes (not released yet) to TCP logging I found that the implementation is not resilient to network problems. On network error, the component was exiting with error and that's it.

* Better error handling (with explanation), skipping logs whenever there is an error. I tried retries, but that was a dead end.
* Better logging
* I removed a bunch of useless interfaces. That may make sense with gRPC AccessLog, but now they were making code hard to read.
* Package `v3` was unnecessary.
* I changed the name from server to streamer and squashed this into one file. It was a gRPC AccessLog _server_ before, but it's not a server anymore, so the name is misleading.
* Dropped useless log `kuma-dp has named pipe feature flag` and added info about proxy in actually useful log in CP.
* Senders were not properly closed when component was stopped.
* Enriched E2E test to check the broken configuration.

Fix #4859

### Checklist prior to review

- [X] Link to docs PR or issue --
- [X] Link to UI issue or PR --
- [X] Is the [issue worked on linked][1]? -- #4859
- [X] The PR does not hardcode values that might break projects that depend on kuma (e.g. "kumahq" as a image registry) --
- [X] The PR will work for both Linux and Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [ ] Unit Tests -- Currently E2E covers it
- [X] E2E Tests --
- [X] Manual Universal Tests --
- [X] Manual Kubernetes Tests --
- [X] Do you need to update [`UPGRADE.md`](/UPGRADE.md)? --
- [X] Does it need to be backported according to the [backporting policy](/CONTRIBUTING.md#backporting)? --

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

File: app/kuma-dp/pkg/dataplane/accesslogs/streamer.go [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+func NewAccessLogStreamer(dataplane kumadp.Dataplane) *accessLogStreamer {
+	return &accessLogStreamer{
+		address: envoy.AccessLogSocketName(dataplane.Name, dataplane.Mesh),
+		senders: map[string]*logSender{},
+	}
+}
+
+func (s *accessLogStreamer) Start(stop <-chan struct{}) error {
+	logger.Info("cleaning existing access log pipe", "file", s.address)
+	err := os.Remove(s.address)
```
Comment (lobkovilya) [inline app/kuma-dp/pkg/dataplane/accesslogs/streamer.go:49]: I know it's a behavior we used to have, but is it possible to have a race here? Like Envoy already started writing some logs to the existing pipe and we're deleting it?

File: app/kuma-dp/pkg/dataplane/accesslogs/streamer.go [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+		return nil
+	}
+}
+
+func (s *accessLogStreamer) cleanup() {
+	s.RLock()
+	defer s.RUnlock()
+	for _, sender := range s.senders {
+		logger.Info("closing connection to the TCP log destination", "address", sender)
+		if err := sender.close(); err != nil {
```
Comment (lobkovilya) [inline app/kuma-dp/pkg/dataplane/accesslogs/streamer.go:91]: maybe also delete it from the `senders` map after closing, otherwise, after ResilientComponent restarts, `senders` won't be empty

Comment (jakubdyszkiewicz) [reply app/kuma-dp/pkg/dataplane/accesslogs/streamer.go:91]: Good point! Fixed. I clear the whole map now.

File: app/kuma-dp/pkg/dataplane/accesslogs/streamer.go (hunk 1 above)
Comment (jakubdyszkiewicz) [reply app/kuma-dp/pkg/dataplane/accesslogs/streamer.go:49]: I did a bit of testing by removing the FIFO in the middle of the process that was running and it recovered. I think I'd leave it for now.

**Review by lobkovilya — APPROVED** [review]

**Comment by jakubdyszkiewicz** [comment]
@mergifyio backport release-1.8
