### PR TITLE
fix(kuma-cp) validate newly generated xDS snapshots

### LINKED ISSUE #2537: xDS builders should validate the type they build
### Summary

In each xDS builder, we should call `.Validate()` on the type so that we can catch any simple errors early.

### PR DESCRIPTION
**Pull request by jpeach**
### Summary

The xDS resource validation is built in to the Go packages, as well as the
Envoy xDS client. Running the validation before we swap the xDS snapshot
in the cache prevents Kuma from sending known-bad configuration to Envoy.

Validation is particularly helpful in tests, since we can ensure that
Kuma is generating valid xDS resources even without a running Envoy to
send them to. This check found a case where the Gateway generator would
generate routes without the require path match.

### Full changelog

N/A

### Issues resolved

Fix #2537.

### Documentation

N/A

### Testing

- [x] Unit tests
- [x] E2E tests
- [ ] Manual testing on Universal
- [ ] Manual testing on Kubernetes 

### Backwards compatibility

- [x] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.

### CODE REVIEW

File: pkg/xds/server/v3/reconcile.go [hunk 1]
```diff
@@ -40,30 +40,71 @@ func (r *reconciler) Reconcile(ctx xds_context.Context, proxy *model.Proxy) erro
...
+				if err := validateResource(resource.Resource); err != nil {
+					reconcileLog.Error(err, "invalid resource", "name", name, "proxy", proxy)
+					return err
+				}
+			}
+		}
+
+		if err := snapshot.Consistent(); err != nil {
+			reconcileLog.Error(err, "inconsistent snapshot", "snapshot", snapshot, "proxy", proxy)
+			return err
```
Comment (jakubdyszkiewicz) [inline pkg/xds/server/v3/reconcile.go:70]: I think we should just return the error. Not log + error. I know there is the same thing already in line 40, but logging should be only on the top level (`log.Error(err, "OnTick() failed")`), otherwise we are duplicating errors.

**Review by jakubdyszkiewicz — APPROVED** [review]

File: pkg/xds/server/v3/reconcile.go (hunk 1 above)
Comment (jpeach) [reply pkg/xds/server/v3/reconcile.go:70]: I removed all the logs except this one. I think that we should keep this because it's the only place that dumps the snapshot itself, which is needed to debug why it is inconsistent (the errors out of go-control-plane are not very helpful for this).
