### PR TITLE
fix(gateway): let Dataplanes take precedence over ExternalServices

### LINKED ISSUE #3024: Discuss the priority semantics of Dataplane and ExternalService conflicts
### Summary

It is possible for both Dataplane and ExternalService resources to claim the same `kuma.io/service` tag. However, traffic is only ever routed to either a dataplane cluster, or an external service cluster, never both.

The mesh code generates endpoints for both Dataplanes and ExternalServices, incidentally processing Dataplanes first, so  Dataplanes get priority in the case of conflicts. The gateway code never generates endpoints for Dataplanes (it just looks in the load assignment cache), so it explicitly checks for matching ExternaServices first.

We should discuss, implement and document the precise semantics that Kuma should apply here.

- [ ] Update docs

### PR DESCRIPTION
**Pull request by michaelbeaumont**
### Summary

Consolidate logic here `Dataplane`s and `Gateway`s.

There are potentially performance implications here.

~Blocked by #3834~

Closes #3024

### CODE REVIEW

File: pkg/plugins/runtime/gateway/cluster_generator.go [hunk 1]
```diff
@@ -43,27 +38,35 @@ func (c *ClusterGenerator) GenerateClusters(ctx xds_context.Context, info Gatewa
...
+		matched := match.ExternalService(info.ExternalServices.Items, mesh_proto.TagSelector(dest.Destination))
+		service := dest.Destination[mesh_proto.ServiceTag]
+
+		firstEndpointExternalService := false
+		if endpoints := info.OutboundEndpoints[service]; len(endpoints) > 0 {
+			ep := endpoints[0]
+			if ep.IsExternalService() {
+				firstEndpointExternalService = true
+			}
+		}
```
Comment (bartsmykla) [inline pkg/plugins/runtime/gateway/cluster_generator.go:50]: maybe:
```suggestion
		var firstEndpointExternalService bool
		if endpoints := info.OutboundEndpoints[service]; len(endpoints) > 0 {
			firstEndpointExternalService = endpoints[0].IsExternalService()
		}
```

**Review by bartsmykla — APPROVED** [review]
lgtm
