### PR TITLE
fix(kuma-dp): reduce size of access log address

### LINKED ISSUE #853: Kuma-sidecar not starting when using Telepresence
### Summary

Telepresence is a really useful tool than allows you to substitute a pod in your kubernetes cluster by a docker image on your local computer. This image helps to understand how it works: 

1_ceyHmoGefCl-EuWleiZFQw
_Image modified from [medium](https://medium.com/swlh/local-development-with-telepresence-256911cb21e9)_

I am using this tool during development to test my new app version directly in the kubernetes cluster (I don't need to have a local test cluster).

The problem is that when I use telepresence to replace one of my pods the kuma-sidecar is not starting alongside the pods set by telepresence in replacement of my normal pod. 
Here are the logs of the kuma-sidecar:

```
2020-06-25T07:07:20.421Z	INFO	Skipping reading config from file
2020-06-25T07:07:20.421Z	INFO	kuma-dp.run	effective configuration	{"config": "controlPlane:\n  apiServer:\n    url: http://kuma-control-plane.kuma-system:5681\ndataplane:\n  mesh: default\n  name: app-dn-deployment-5ab90d93b67a4f72be34651114fd7de4-67679bbrtq74.datanostrum\n  drainTime: 30s\ndataplaneRuntime:\n  binaryPath: envoy\n  dataplaneTokenPath: /var/run/secrets/kubernetes.io/serviceaccount/token\n"}
2020-06-25T07:07:20.425Z	INFO	kuma-dp.run	picked a free port for Envoy Admin API to listen on	{"port": "9901"}
2020-06-25T07:07:20.425Z	INFO	kuma-dp.run	generated Envoy configuration will be stored in a temporary directory	{"dir": "/tmp/kuma-dp-553564296"}
2020-06-25T07:07:20.425Z	INFO	kuma-dp.run	starting Kuma DP	{"version": "0.5.1"}
2020-06-25T07:07:20.426Z	ERROR	kuma-dp.run	error while running Kuma DP	{"error": "listen unix /tmp/kuma-access-logs-app-dn-deployment-5ab90d93b67a4f72be34651114fd7de4-67679bbrtq74.datanostrum-default.sock: bind: invalid argument"}
Error: listen unix /tmp/kuma-access-logs-app-dn-deployment-5ab90d93b67a4f72be34651114fd7de4-67679bbrtq74.datanostrum-default.sock: bind: invalid argument
```` 

### Steps To Reproduce

1. With telepresence installed locally and un pod in your kubernetes cluster.
2. Run a command similar to:
```
telepresence --swap-deployment app-dn-deployment --namespace myNameSpace --docker-run --rm -p 5005:5005 app-dn:latest
```
3. Use kubectl to see that the kuma-sidecar is not starting and to see the logs
```
kubectl get pods -n myNameSpace
kubectl logs app-dn-deployment-5ab90d93b67a4f72be34651114fd7de4-67679bbrtq74 kuma-sidecar -n myNameSpace
```

### Additional Details & Logs

- Kubernetes version: 1.7.5-1
- Kuma version: 0.5.1
- Telepresence version: 0.105

### PR DESCRIPTION
**Pull request by xbauquet**
When the name of the dataplane is too long an error stop the side-car
from starting. This update reduces the size of the address and log an
explicit error if the address is still too long.

* reduce the size of access log address replacing 'kuma-access-logs' by
'kal'
* add explicit error log if the size of the address is still too long

Fix #853

### CODE REVIEW

File: app/kuma-dp/pkg/dataplane/accesslogs/server.go [hunk 1]
```diff
@@ -33,10 +33,23 @@ func (s *accessLogServer) NeedLeaderElection() bool {
 }
 
 func NewAccessLogServer(dataplane kumadp.Dataplane) *accessLogServer {
+
+	// Log an explicit error when access log address is too long
+	// see: https://man7.org/linux/man-pages/man7/unix.7.html
+	// see: issue #853
```
Comment (nickolaev) [inline app/kuma-dp/pkg/dataplane/accesslogs/server.go:38]: Please remove the reference to the issue here. The best way to track this will be through following the git history of this particular piece of code.

Comment (xbauquet) [reply app/kuma-dp/pkg/dataplane/accesslogs/server.go]: Done :)

**Comment by lobkovilya** [comment]
Great! @xbauquet could you please run `make check` and commit the result? We have to run it before every push, so maybe it will be easier to have it as a git hook. `make check` runs `goimports`, `go mod tidy` and etc, otherwise `check` job is failed on CI

File: app/kuma-dp/pkg/dataplane/accesslogs/server.go [hunk 2]
```diff
@@ -33,10 +33,21 @@ func (s *accessLogServer) NeedLeaderElection() bool {
...
+	// see: https://man7.org/linux/man-pages/man7/unix.7.html
+	var address = fmt.Sprintf("/tmp/kal-%s-%s.sock", dataplane.Name, dataplane.Mesh)
+	if len(address) > 108 {
+		logger.Error(nil, fmt.Sprintf(`The name of your dataplane is too long: %s. 
+										It is important that the address to store your access logs doesn't have more than 108 characters. 
+										The actuall address is: %s.
+										Please reduce the size of your dataplane name.`,
+			dataplane.Name,
+			address))
+	}
```
Comment (jakubdyszkiewicz) [inline app/kuma-dp/pkg/dataplane/accesslogs/server.go:46]: Can we do something more automatic here?
We are not so attached to this name, to be honest. We can just as well either:
1) trim the name to 108 chars
2) use UUID

As long as we log this path to the file, it's fine.

Comment (xbauquet) [reply app/kuma-dp/pkg/dataplane/accesslogs/server.go:46]: I thought about using a UUID but I thought it would complicate debug. 
In which file do you want to log the path ? In the normal logs (using `logger.Info(...)` ) ?

File: go.mod [hunk 3]
```diff
@@ -22,7 +22,7 @@ require (
 	github.com/go-logr/zapr v0.1.0
 	github.com/gogo/protobuf v1.3.1
 	github.com/golang-migrate/migrate/v4 v4.8.0
-	github.com/golang/protobuf v1.3.2
+	github.com/golang/protobuf v1.4.1
```
[the remark this answers is not in the document]
Comment (xbauquet) [reply go.mod:25]: No good reasons, this came with the `make check` requested by @lobkovilya.
I'm having troubles running `make check` anyway. It always finishes with `make: *** [vet] Error` but I don't have any error logs on my terminal. 
I'm a bit lost on it as I don't know much about go.

[the remark this answers is not in the document]
Comment (xbauquet) [reply go.mod]: It seems like it was a problem with the versions of the tools installed on my computer.
Using `make dev/tools/all` and redoing the `make check` fixed the problem.

File: app/kuma-dp/pkg/dataplane/accesslogs/server.go [hunk 4]
```diff
@@ -33,10 +34,15 @@ func (s *accessLogServer) NeedLeaderElection() bool {
 }
 
 func NewAccessLogServer(dataplane kumadp.Dataplane) *accessLogServer {
+	id := guuid.New()
+	var address = fmt.Sprintf("/tmp/%s.sock", id)
+	logger.Info("Access log for pod",
+		"pod", fmt.Sprintf("/tmp/kal-%s-%s.sock", dataplane.Name, dataplane.Mesh),
+		"address", fmt.Sprintf("unix://%s", address))
```
Comment (jakubdyszkiewicz) [inline app/kuma-dp/pkg/dataplane/accesslogs/server.go:41]: Log is not needed here after all. We log the address on server start

File: app/kuma-dp/pkg/dataplane/accesslogs/server.go [hunk 5]
```diff
@@ -33,10 +34,15 @@ func (s *accessLogServer) NeedLeaderElection() bool {
 }
 
 func NewAccessLogServer(dataplane kumadp.Dataplane) *accessLogServer {
+	id := guuid.New()
```
Comment (jakubdyszkiewicz) [inline app/kuma-dp/pkg/dataplane/accesslogs/server.go:37]: please use `core.NewUUID()` (from `/pkg/core/alias.go`)
