### PR TITLE
fix(xds): use listener name as vhost fallback

### LINKED ISSUE #15580: Inbound listener generation failure once kuma.io/service not defined
### Kuma Version

master

### Describe the bug

```2026-02-10T14:46:41.330Z	ERROR	xds.server.dataplane-sync-watchdog	OnTick() failed	{"dataplaneKey": {"Mesh":"default","Name":"test-server"}, "error": "could not reconcile: failed to generate a snapshot: imports[0]{name=\"default-proxy\"}: generator.InboundProxyGenerator failed: dataplane.networking.inbound[0]: could not generate listener inbound:127.0.0.1:9000: virtual host name is required, but it was not provided", "errorVerbose": "imports[0]{name=\"default-proxy\"}: generator.InboundProxyGenerator failed: dataplane.networking.inbound[0]: could not generate listener inbound:127.0.0.1:9000: virtual host name is required, but it was not provided\nfailed to generate a snapshot\ngithub.com/kumahq/kuma/v2/pkg/xds/server/v3.(*reconciler).Reconcile\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/xds/server/v3/reconcile.go:57\ngithub.com/kumahq/kuma/v2/pkg/xds/sync.(*DataplaneWatchdog).syncDataplane\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/xds/sync/dataplane_watchdog.go:196\ngithub.com/kumahq/kuma/v2/pkg/xds/sync.(*DataplaneWatchdog).Sync\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/xds/sync/dataplane_watchdog.go:83\ngithub.com/kumahq/kuma/v2/pkg/xds/sync.(*dataplaneWatchdogFactory).NewWithStreamCtx.func2\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/xds/sync/dataplane_watchdog_factory.go:49\ngithub.com/kumahq/kuma/v2/pkg/util/watchdog.(*SimpleWatchdog).onTick\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/util/watchdog/watchdog.go:98\ngithub.com/kumahq/kuma/v2/pkg/util/watchdog.(*SimpleWatchdog).Start\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/util/watchdog/watchdog.go:63\ngithub.com/kumahq/kuma/v2/pkg/xds/server/callbacks.(*dataplaneSyncTracker).OnProxyConnected.func1\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/xds/server/callbacks/dataplane_sync_tracker.go:58\nruntime.goexit\n\truntime/asm_amd64.s:1693\ncould not reconcile\ngithub.com/kumahq/kuma/v2/pkg/xds/sync.(*DataplaneWatchdog).syncDataplane\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/xds/sync/dataplane_watchdog.go:198\ngithub.com/kumahq/kuma/v2/pkg/xds/sync.(*DataplaneWatchdog).Sync\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/xds/sync/dataplane_watchdog.go:83\ngithub.com/kumahq/kuma/v2/pkg/xds/sync.(*dataplaneWatchdogFactory).NewWithStreamCtx.func2\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/xds/sync/dataplane_watchdog_factory.go:49\ngithub.com/kumahq/kuma/v2/pkg/util/watchdog.(*SimpleWatchdog).onTick\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/util/watchdog/watchdog.go:98\ngithub.com/kumahq/kuma/v2/pkg/util/watchdog.(*SimpleWatchdog).Start\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/util/watchdog/watchdog.go:63\ngithub.com/kumahq/kuma/v2/pkg/xds/server/callbacks.(*dataplaneSyncTracker).OnProxyConnected.func1\n\tgithub.com/kumahq/kuma/v2@v2.13.1-0.20260205180907-00714b786fb8/pkg/xds/server/callbacks/dataplane_sync_tracker.go:58\nruntime.goexit\n\truntime/asm_amd64.s:1693"}```

### To Reproduce

1. Deploy Kuma on universa
2. Don't use transparent proxy
3. Don't define kuma.io/service on the inbound 

### Expected behavior

_No response_

### Additional context (optional)

_No response_

### PR DESCRIPTION
**Pull request by Automaat**
## Motivation

When deploying on Universal without transparent proxy and without
defining `kuma.io/service` on an HTTP inbound, the control plane
fails with:

```
virtual host name is required, but it was not provided
```

`FilterChainBuilder` derives `virtualHostName` from the service tag.
With no tag present and unified naming disabled, the name is an empty
string, which the virtual host builder rejects.

Fixes #15580

## Implementation information

When `virtualHostName` is empty (service tag absent, unified naming
off), fall back to `inbound:IP:port` — the inbound listener name —
for both `routeConfigName` and `virtualHostName`. This is always
unique and non-empty.

Added test case 10: HTTP inbound without `kuma.io/service` tag,
with golden file confirming the listener is generated correctly.

> Changelog: fix(xds): use listener name as vhost fallback when kuma.io/service absent

### CODE REVIEW

File: pkg/xds/generator/inbound_proxy_generator.go [hunk 1]
```diff
@@ -155,6 +155,12 @@ func FilterChainBuilder(
 	contextualName := naming.MustContextualInboundName(proxy.Dataplane, endpoint.InboundName)
 	routeConfigName := getName(contextualName, envoy_names.GetInboundRouteName(service))
 	virtualHostName := getName(contextualName, service)
+	if virtualHostName == "" {
+		// kuma.io/service tag not set; fall back to the listener address
```
Comment (lahabana) [inline pkg/xds/generator/inbound_proxy_generator.go:159]: When is `kuma.io/service` tag not set?

Comment (Automaat) [reply pkg/xds/generator/inbound_proxy_generator.go:159]: when we have inbound tags disabled, which we can do now

Comment (lahabana) [reply pkg/xds/generator/inbound_proxy_generator.go:159]: But wasn't inbounds tags disabled only valid with unified naming? There isn't a MADR for it so I can't remember whether we made this decision or not but it looks to me like an acceptable requirement no?

Comment (Automaat) [reply pkg/xds/generator/inbound_proxy_generator.go:159]: you can use it without unified naming, there are no requirement for disabling inbound tags
