### PR TITLE
fix: warn when using deprecated token id

### LINKED ISSUE #4006: Warn when using deprecated serial numbers in token
### Description

Since 1.4 we rely on kid, not on serial number.

I don't think we did a good enough job recommending regeneration token, so it may not be feasible to remove it in the next version.

### PR DESCRIPTION
**Pull request by lahabana**
Tracking removal with #5519

Fix #4006

Signed-off-by: Charly Molter <charly.molter@konghq.com>

### Checklist prior to review

- [x] Link to docs PR or issue --
- [x] Link to UI issue or PR --
- [x] Is the [issue worked on linked][1]? --
- [x] The PR does not hardcode values that might break projects that depend on kuma (e.g. "kumahq" as a image registry) --
- x ] The PR will work for both Linux and Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
- [x] Unit Tests --
- [x] E2E Tests --
- [x] Manual Universal Tests --
- [x] Manual Kubernetes Tests --
- [x] Do you need to update [`UPGRADE.md`](../blob/master/UPGRADE.md)? --
- [x] Does it need to be backported according to the [backporting policy](../blob/master/CONTRIBUTING.md#backporting)? --
- [x] Do you need to explicitly set a [`> Changelog:` entry here](../blob/master/CONTRIBUTING.md#submitting-a-patch) or add a `ci/` label to run fewer/more tests?

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

### CODE REVIEW

**Review by lukidzi — APPROVED** [review]

File: pkg/core/tokens/validator.go [hunk 1]
```diff
@@ -33,24 +38,34 @@ var _ Validator = &jwtTokenValidator{}
 
 func (j *jwtTokenValidator) ParseWithValidation(ctx context.Context, rawToken Token, claims Claims) error {
 	token, err := jwt.ParseWithClaims(rawToken, claims, func(token *jwt.Token) (interface{}, error) {
-		serialNumber, err := tokenSerialNumber(token, claims)
+		serialNumberRaw, exists := token.Header[KeyIDHeader]
+		if !exists {
+			if _, ok := claims.(KeyIDFallback); ok {
+				// KID wasn't supported in the past, so we use a marker interface to indicate which tokens were allowed
+				// This will be removed with https://github.com/kumahq/kuma/issues/5519
+				log.Info("[WARNING] Using token with KID header, you should rotate this token as it will not be valid in future versions of Kuma", "jti", claims.ID(), KeyIDHeader, 0)
```
Comment (jakubdyszkiewicz) [inline pkg/core/tokens/validator.go:46]: I'd consider logging claims. It's safe to log, it does not contain secret. It might be a bit hard to locate a token by ID.

Additionally, we don't now what type of token it is

File: pkg/core/tokens/validator.go [hunk 2]
```diff
@@ -2,14 +2,19 @@ package tokens
...
 	"strconv"
 
 	"github.com/golang-jwt/jwt/v4"
 	"github.com/pkg/errors"
 
 	store_config "github.com/kumahq/kuma/pkg/config/core/resources/store"
+	"github.com/kumahq/kuma/pkg/core"
 )
 
+var log = core.Log.WithName("tokens-validator")
```
Comment (jakubdyszkiewicz) [inline pkg/core/tokens/validator.go:16]: I'd pass it to `NewValidator` with indication what type of token it is. Something like
```
NewValidator(..., ..., core.Log.WithName("tokens-validator").WithName("zone-token"))
```
